# Generated by Django 5.2.3 on 2025-06-18 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='생산일자')),
                ('tonnage', models.CharField(max_length=10, verbose_name='톤수')),
                ('model', models.CharField(max_length=50, verbose_name='모델명')),
                ('section', models.CharField(choices=[('C/A', 'C/A'), ('B/C', 'B/C'), ('COVER', 'COVER')], max_length=10, verbose_name='구분')),
                ('plan_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='계획수량')),
                ('actual_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='실제수량')),
                ('reported_defect', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='보고불량수')),
                ('actual_defect', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='실제불량수')),
                ('operation_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가동시간(분)')),
                ('total_time', models.IntegerField(default=1440, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총시간(분)')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '사출 보고서',
                'verbose_name_plural': '사출 보고서 목록',
                'ordering': ['-date', 'tonnage', 'model'],
            },
        ),
    ]
