# Generated by Django 5.2.3 on 2025-06-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionreport',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료 일시'),
        ),
        migrations.AddField(
            model_name='injectionreport',
            name='machine_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='사출기 번호'),
        ),
        migrations.AddField(
            model_name='injectionreport',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작 일시'),
        ),
        migrations.AlterField(
            model_name='injectionreport',
            name='tonnage',
            field=models.CharField(max_length=10, verbose_name='형체력(T)'),
        ),
    ]
