# Generated by Django 5.2.3 on 2025-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0002_injectionreport_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='모델명')),
                ('type', models.CharField(max_length=50, verbose_name='구분')),
                ('fg_part_no', models.CharField(max_length=100, verbose_name='成品 PART-NO')),
                ('wip_part_no', models.CharField(max_length=100, verbose_name='半成品 PART-NO')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품 목록',
                'ordering': ['model', 'type'],
                'unique_together': {('model', 'type')},
            },
        ),
    ]
