# Generated by Django 5.2.3 on 2025-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, verbose_name='Part No')),
                ('model_code', models.CharField(max_length=100, verbose_name='모델 코드')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('mold_type', models.CharField(blank=True, max_length=50, verbose_name='금형 타입')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='색상')),
                ('resin_type', models.CharField(blank=True, max_length=50, verbose_name='Resin 종류')),
                ('resin_code', models.CharField(blank=True, max_length=50, verbose_name='Resin 코드')),
                ('net_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Net 중량(g)')),
                ('sr_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='S/R 중량(g)')),
                ('tonnage', models.PositiveIntegerField(blank=True, null=True, verbose_name='형체력(T)')),
                ('cycle_time_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='사이클 타임(초)')),
                ('efficiency_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='효율(%)')),
                ('cavity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cavity')),
                ('resin_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resin Loss(%)')),
                ('defect_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='불량률(%)')),
                ('valid_from', models.DateField(verbose_name='유효 시작일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '품목 스펙',
                'verbose_name_plural': '품목 스펙 목록',
                'ordering': ['part_no', '-valid_from'],
                'unique_together': {('part_no', 'valid_from')},
            },
        ),
    ]
