# Generated by Django 5.2.3 on 2025-07-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0008_engineeringchangeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.TextField(blank=True, verbose_name='변경 사유')),
                ('change_details', models.TextField(blank=True, verbose_name='변경 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eco_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='injection.engineeringchangeorder')),
                ('part_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injection.partspec')),
            ],
            options={
                'verbose_name': 'ECO 상세',
                'verbose_name_plural': 'ECO 상세 목록',
                'unique_together': {('eco_header', 'part_spec')},
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='재고 수량')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시각')),
                ('part_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injection.partspec')),
            ],
            options={
                'verbose_name': '재고 스냅샷',
                'verbose_name_plural': '재고 스냅샷',
                'indexes': [models.Index(fields=['part_spec', '-collected_at'], name='injection_i_part_sp_6150be_idx')],
            },
        ),
    ]
