# Generated by Django 5.2.3 on 2025-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0009_ecodetail_inventorysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecodetail',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10, verbose_name='상태'),
        ),
    ]
