# Generated by Django 5.2.3 on 2025-07-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0010_ecodetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoPartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, unique=True, verbose_name='Part No')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('model_code', models.CharField(blank=True, max_length=100, verbose_name='모델 코드')),
                ('eco_category', models.CharField(blank=True, max_length=50, verbose_name='ECO 카테고리')),
                ('change_history', models.TextField(blank=True, verbose_name='변경 이력')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'ECO Part 스펙',
                'verbose_name_plural': 'ECO Part 스펙 목록',
                'ordering': ['part_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='ecodetail',
            options={'ordering': ['eco_header', 'part_spec'], 'verbose_name': 'ECO 상세', 'verbose_name_plural': 'ECO 상세 목록'},
        ),
        migrations.AlterModelOptions(
            name='inventorysnapshot',
            options={'ordering': ['-collected_at'], 'verbose_name': '재고 스냅샷', 'verbose_name_plural': '재고 스냅샷 목록'},
        ),
        migrations.RemoveIndex(
            model_name='inventorysnapshot',
            name='injection_i_part_sp_6150be_idx',
        ),
        migrations.AddField(
            model_name='ecodetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='ecodetail',
            name='change_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='변경 사유'),
        ),
        migrations.AlterField(
            model_name='ecodetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='ecodetail',
            name='part_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecodetail', to='injection.partspec'),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='수집일시'),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='part_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='injection.partspec'),
        ),
        migrations.AlterField(
            model_name='inventorysnapshot',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='ecodetail',
            name='eco_part_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_details', to='injection.ecopartspec'),
        ),
    ]
