# Generated by Django 5.2.3 on 2025-07-18 05:18

from django.db import migrations


def migrate_eco_data_to_ecopartspec(apps, schema_editor):
    """기존 ECO 데이터를 EcoPartSpec으로 마이그레이션"""
    EcoDetail = apps.get_model('injection', 'EcoDetail')
    EcoPartSpec = apps.get_model('injection', 'EcoPartSpec')
    
    # 기존 EcoDetail에서 part_spec이 있는 데이터들을 처리
    for eco_detail in EcoDetail.objects.filter(part_spec__isnull=False):
        part_spec = eco_detail.part_spec
        
        # 해당 Part No의 EcoPartSpec이 있는지 확인
        eco_part_spec, created = EcoPartSpec.objects.get_or_create(
            part_no=part_spec.part_no,
            defaults={
                'description': part_spec.description or '',
                'model_code': part_spec.model_code or ''
            }
        )
        
        # EcoDetail의 eco_part_spec 필드 업데이트
        eco_detail.eco_part_spec = eco_part_spec
        eco_detail.save(update_fields=['eco_part_spec'])


def reverse_migrate_eco_data(apps, schema_editor):
    """마이그레이션 되돌리기 (필요시)"""
    EcoDetail = apps.get_model('injection', 'EcoDetail')
    EcoDetail.objects.filter(eco_part_spec__isnull=False).update(eco_part_spec=None)


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0011_add_ecopartspec_safe'),
    ]

    operations = [
        migrations.RunPython(migrate_eco_data_to_ecopartspec, reverse_migrate_eco_data),
    ]
