# Generated by Django 5.2.3 on 2025-08-20 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0012_migrate_eco_data_to_ecopartspec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='성명')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('reason', models.TextField(verbose_name='가입 사유')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거부')], default='pending', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('temporary_password', models.CharField(blank=True, max_length=100, verbose_name='임시 비밀번호')),
                ('can_view_injection', models.BooleanField(default=False, verbose_name='사출 조회 권한')),
                ('can_edit_injection', models.BooleanField(default=False, verbose_name='사출 편집 권한')),
                ('can_view_machining', models.BooleanField(default=False, verbose_name='가공 조회 권한')),
                ('can_edit_machining', models.BooleanField(default=False, verbose_name='가공 편집 권한')),
                ('can_view_eco', models.BooleanField(default=False, verbose_name='ECO 조회 권한')),
                ('can_edit_eco', models.BooleanField(default=False, verbose_name='ECO 편집 권한')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='재고 조회 권한')),
                ('can_edit_inventory', models.BooleanField(default=False, verbose_name='재고 편집 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
            ],
            options={
                'verbose_name': '가입 요청',
                'verbose_name_plural': '가입 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
