# Generated by Django 5.2.3 on 2025-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0013_userregistrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='reason',
            field=models.TextField(blank=True, verbose_name='가입 사유'),
        ),
    ]
