# Generated by Django 5.2.3 on 2025-08-21 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0014_alter_userregistrationrequest_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_injection', models.BooleanField(default=False, verbose_name='사출 조회 권한')),
                ('can_edit_injection', models.BooleanField(default=False, verbose_name='사출 편집 권한')),
                ('can_view_machining', models.BooleanField(default=False, verbose_name='가공 조회 권한')),
                ('can_edit_machining', models.BooleanField(default=False, verbose_name='가공 편집 권한')),
                ('can_view_eco', models.BooleanField(default=False, verbose_name='ECO 조회 권한')),
                ('can_edit_eco', models.BooleanField(default=False, verbose_name='ECO 편집 권한')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='재고 조회 권한')),
                ('can_edit_inventory', models.BooleanField(default=False, verbose_name='재고 편집 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 권한 프로필',
                'verbose_name_plural': '사용자 권한 프로필 목록',
            },
        ),
    ]
