# Generated by Django 5.2.3 on 2025-08-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0016_auto_20250822_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_using_temp_password',
            field=models.BooleanField(default=False, verbose_name='임시 비밀번호 사용 중'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 비밀번호 변경일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_required',
            field=models.BooleanField(default=False, verbose_name='비밀번호 재설정 필요'),
        ),
    ]
