# Generated by Django 5.2.3 on 2025-09-16 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0018_auto_20250916_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionreport',
            name='idle_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부동시간(분)'),
        ),
    ]
