# Generated by Django 5.2.3 on 2025-09-17 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0019_alter_injectionreport_idle_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTimeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_date', models.DateTimeField(auto_now_add=True, verbose_name='설정일시')),
                ('machine_no', models.PositiveSmallIntegerField(verbose_name='사출기 번호')),
                ('part_no', models.CharField(max_length=100, verbose_name='Part No.')),
                ('target_cycle_time', models.PositiveIntegerField(verbose_name='목표 사이클 타임(초)')),
                ('test_cycle_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='테스트 사이클 타임(초)')),
                ('approved_cycle_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='승인된 사이클 타임(초)')),
                ('status', models.CharField(choices=[('SETUP', '설정중'), ('TESTING', '테스트중'), ('APPROVED', '승인완료'), ('REJECTED', '반려')], default='SETUP', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('note', models.TextField(blank=True, verbose_name='설정 비고')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='반려 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_setups', to=settings.AUTH_USER_MODEL)),
                ('setup_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사이클 타임 셋업',
                'verbose_name_plural': '사이클 타임 셋업 목록',
                'ordering': ['-setup_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleTimeTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_datetime', models.DateTimeField(auto_now_add=True, verbose_name='테스트 시간')),
                ('actual_cycle_time', models.PositiveIntegerField(verbose_name='실제 사이클 타임(초)')),
                ('test_qty', models.PositiveSmallIntegerField(default=1, verbose_name='테스트 수량')),
                ('quality_ok', models.BooleanField(default=True, verbose_name='품질 양호')),
                ('note', models.TextField(blank=True, verbose_name='테스트 비고')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to='injection.cycletimesetup')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사이클 타임 테스트 기록',
                'verbose_name_plural': '사이클 타임 테스트 기록 목록',
                'ordering': ['-test_datetime'],
            },
        ),
    ]
