# Generated by Django 5.2.3 on 2025-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0020_cycletimesetup_cycletimetestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionMonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50, verbose_name='설비명')),
                ('device_code', models.CharField(db_index=True, max_length=100, verbose_name='Device Code')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='측정시간')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='생산량')),
                ('oil_temperature', models.FloatField(blank=True, null=True, verbose_name='오일온도')),
            ],
            options={
                'verbose_name': '사출기 모니터링 기록',
                'verbose_name_plural': '사출기 모니터링 기록 목록',
                'ordering': ['-timestamp', 'machine_name'],
                'unique_together': {('device_code', 'timestamp')},
            },
        ),
    ]
