# Generated by Django 5.2.3 on 2025-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0021_injectionmonitoringrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletimesetup',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='모델 코드'),
        ),
    ]
