# Generated by Django 5.2.3 on 2025-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0022_cycletimesetup_model_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletimesetup',
            name='approved_cycle_time',
        ),
        migrations.RemoveField(
            model_name='cycletimesetup',
            name='test_cycle_time',
        ),
        migrations.AddField(
            model_name='cycletimesetup',
            name='mean_cycle_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='평균 사이클 타임(초)'),
        ),
        migrations.AddField(
            model_name='cycletimesetup',
            name='standard_cycle_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='표준 사이클 타임(초)'),
        ),
    ]
