# Generated by Django 5.2.3 on 2025-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0023_remove_cycletimesetup_approved_cycle_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletimesetup',
            name='personnel_count',
            field=models.FloatField(blank=True, null=True, verbose_name='배치인원수'),
        ),
    ]
