# Generated by Django 5.2.3 on 2025-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0025_alter_cycletimesetup_personnel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletimesetup',
            name='personnel_count',
            field=models.FloatField(default=1.5, verbose_name='배치인원수'),
        ),
    ]
