# Generated by Django 5.2.3 on 2025-09-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0026_alter_cycletimesetup_personnel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_edit_eco',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_edit_injection',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_edit_inventory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_edit_machining',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_eco',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_inventory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_machining',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_edit_eco',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_edit_injection',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_edit_inventory',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_edit_machining',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_view_eco',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_view_inventory',
        ),
        migrations.RemoveField(
            model_name='userregistrationrequest',
            name='can_view_machining',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_assembly',
            field=models.BooleanField(default=False, verbose_name='가공 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_development',
            field=models.BooleanField(default=False, verbose_name='개발/ECO 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_quality',
            field=models.BooleanField(default=False, verbose_name='품질 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_sales',
            field=models.BooleanField(default=False, verbose_name='영업/재고 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_view_assembly',
            field=models.BooleanField(default=False, verbose_name='가공 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_view_development',
            field=models.BooleanField(default=False, verbose_name='개발/ECO 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_view_quality',
            field=models.BooleanField(default=False, verbose_name='품질 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_view_sales',
            field=models.BooleanField(default=False, verbose_name='영업/재고 메뉴 접근'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_injection',
            field=models.BooleanField(default=False, verbose_name='사출 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_injection',
            field=models.BooleanField(default=False, verbose_name='사출 메뉴 접근'),
        ),
    ]
