# Generated by Django 5.2.3 on 2025-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0027_remove_userprofile_can_edit_eco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_assembly',
            field=models.BooleanField(default=False, verbose_name='가공 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_development',
            field=models.BooleanField(default=False, verbose_name='개발/ECO 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_injection',
            field=models.BooleanField(default=False, verbose_name='사출 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_quality',
            field=models.BooleanField(default=False, verbose_name='품질 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_sales',
            field=models.BooleanField(default=False, verbose_name='영업/재고 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_edit_assembly',
            field=models.BooleanField(default=False, verbose_name='가공 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_edit_development',
            field=models.BooleanField(default=False, verbose_name='개발/ECO 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_edit_injection',
            field=models.BooleanField(default=False, verbose_name='사출 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_edit_quality',
            field=models.BooleanField(default=False, verbose_name='품질 편집/삭제 권한'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='can_edit_sales',
            field=models.BooleanField(default=False, verbose_name='영업/재고 편집/삭제 권한'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_assembly',
            field=models.BooleanField(default=True, verbose_name='가공 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_development',
            field=models.BooleanField(default=True, verbose_name='개발/ECO 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_injection',
            field=models.BooleanField(default=True, verbose_name='사출 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_quality',
            field=models.BooleanField(default=True, verbose_name='품질 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_sales',
            field=models.BooleanField(default=True, verbose_name='영업/재고 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_assembly',
            field=models.BooleanField(default=True, verbose_name='가공 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_development',
            field=models.BooleanField(default=True, verbose_name='개발/ECO 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_injection',
            field=models.BooleanField(default=True, verbose_name='사출 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_quality',
            field=models.BooleanField(default=True, verbose_name='품질 메뉴 접근'),
        ),
        migrations.AlterField(
            model_name='userregistrationrequest',
            name='can_view_sales',
            field=models.BooleanField(default=True, verbose_name='영업/재고 메뉴 접근'),
        ),
    ]
