# Generated by Django 5.2.3 on 2025-09-29 06:05

from django.db import migrations


def update_existing_user_permissions(apps, schema_editor):
    """기존 사용자들의 조회 권한을 모두 True로 설정"""
    UserProfile = apps.get_model('injection', 'UserProfile')

    # 모든 기존 사용자에게 조회 권한 부여
    UserProfile.objects.filter(
        can_view_injection=False
    ).update(
        can_view_injection=True,
        can_view_assembly=True,
        can_view_quality=True,
        can_view_sales=True,
        can_view_development=True
    )


def reverse_user_permissions(apps, schema_editor):
    """롤백 시 기존 사용자들의 조회 권한을 False로 되돌림"""
    UserProfile = apps.get_model('injection', 'UserProfile')

    # 조회 권한을 False로 되돌림 (기존 동작과 동일)
    UserProfile.objects.update(
        can_view_injection=False,
        can_view_assembly=False,
        can_view_quality=False,
        can_view_sales=False,
        can_view_development=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0028_userprofile_can_edit_assembly_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_user_permissions,
            reverse_user_permissions,
        ),
    ]