# Generated by Django 5.2.3 on 2025-10-13 08:38

from django.db import migrations


def fix_assembly_view_permissions(apps, schema_editor):
    """모든 기존 사용자에게 가공 조회 권한 부여"""
    UserProfile = apps.get_model('injection', 'UserProfile')
    User = apps.get_model('auth', 'User')
    
    # 모든 사용자 프로필의 가공 조회 권한을 True로 설정
    UserProfile.objects.all().update(can_view_assembly=True)
    
    # 프로필이 없는 사용자들을 위해 프로필 생성
    users_without_profile = User.objects.filter(profile__isnull=True)
    for user in users_without_profile:
        UserProfile.objects.create(
            user=user,
            can_view_assembly=True,
            can_view_injection=True,
            can_view_quality=True,
            can_view_sales=True,
            can_view_development=True,
        )


def reverse_fix_assembly_permissions(apps, schema_editor):
    """롤백 함수 (필요시)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0029_update_existing_user_permissions'),
    ]

    operations = [
        migrations.RunPython(
            fix_assembly_view_permissions,
            reverse_fix_assembly_permissions
        ),
    ]
