# Generated by Django 5.2.3 on 2026-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0032_grant_all_view_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='부서'),
        ),
    ]
