# Generated by Django 5.2.3 on 2026-09-16 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0040_userprofile_can_confirm_moulds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionCycleTimeBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=100)),
                ('machine_number', models.PositiveSmallIntegerField(db_index=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('business_date', models.DateField(db_index=True)),
                ('bucket_start', models.DateTimeField()),
                ('calculation_version', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('source_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('source_day_sample_count', models.PositiveIntegerField(default=0)),
                ('source_preservation_note', models.CharField(blank=True, default='', max_length=64)),
                ('archived_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bucket_start', 'machine_number', 'device_code'],
                'indexes': [models.Index(fields=['business_date', 'machine_number'], name='inj_ct_date_machine_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_code', 'bucket_start'), name='inj_ct_device_hour_uniq')],
            },
        ),
        migrations.CreateModel(
            name='InjectionCycleTimeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('source_hash', models.CharField(max_length=64)),
                ('calculation_version', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='injection.injectioncycletimebucket')),
            ],
            options={
                'ordering': ['bucket_id', 'revision'],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'revision'), name='inj_ct_bucket_revision_uniq')],
            },
        ),
    ]
