"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import logging
from decouple import config
import dj_database_url
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file for local development
try:
    from dotenv import load_dotenv
    # Local .env should win over stray machine-level env vars so dev matches the repo config.
    load_dotenv(BASE_DIR / '.env', override=True)
except ImportError:
    pass

# 환경 설정
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-wh%&py10w)!ug#vdky(q+f8+5q0!!@nz+5+-_e$g_^n8=wrf&i')

def _parse_debug(value):
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 't', 'yes', 'y', 'on', 'debug', 'development', 'dev'}:
        return True
    if normalized in {'0', 'false', 'f', 'no', 'n', 'off', 'release', 'production', 'prod', ''}:
        return False
    return False


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _parse_debug(config('DEBUG', default='False'))

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    config('RENDER_EXTERNAL_HOSTNAME', default='wj-reporting-backend.onrender.com'),
    config('ADDITIONAL_ALLOWED_HOST', default=''),
]

# 빈 문자열 제거
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]


# Application definition

# First-password activation is separate from existing-user MES connections.
ACCOUNT_ACTIVATION_ENABLED = config('ACCOUNT_ACTIVATION_ENABLED', default=False, cast=bool)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Cloudinary (must be after staticfiles)
    'cloudinary_storage',
    'cloudinary',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    # 'django_celery_beat',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    # Local apps
    'injection',
    'assembly',
    'sales',
    'overview',
    'inventory',
    'quality',
    'production',
    'ai_core',
    'analytics',
    'mes_oauth',
]
if ACCOUNT_ACTIVATION_ENABLED:
    INSTALLED_APPS.append('account_activation')

MIDDLEWARE = [
    'mes_oauth.security.OAuthQueryRedactionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.middleware.DisableCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mes_oauth.connection_views.BridgeRestrictionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware for API handling
    'config.middleware.NoCacheAPIMiddleware',
    'config.middleware.APINotFoundMiddleware',
]
if ACCOUNT_ACTIVATION_ENABLED:
    MIDDLEWARE.insert(0, 'account_activation.security.ActivationBoundaryMiddleware')

# 보안 설정
if ENVIRONMENT == 'production':
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1년
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CORS 설정
CORS_ALLOW_ALL_ORIGINS = True  # 연결 안정성을 위해 허용 (운영 환경)
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-ai-worker-token',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_PREFLIGHT_MAX_AGE = 86400


# CSRF 신뢰 출처 (프론트엔드 도메인)
CSRF_TRUSTED_ORIGINS = [
    "https://wj-reporting.onrender.com",
    "https://wj-reporting-backend.onrender.com",
]



# Explicit cookie controls let OAuth activation require HTTPS cookies without
# changing ENVIRONMENT and its unrelated HSTS settings. Existing defaults stay.
SESSION_COOKIE_SECURE = ENVIRONMENT == 'production' or config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = ENVIRONMENT == 'production' or config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# 프로덕션 환경에서 쿠키 보안 설정
if ENVIRONMENT == 'production':
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'config.authentication.ScopedJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    # API 응답 캐시 방지 (항상 최신 데이터)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # 404/500 에러도 JSON으로 반환
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'static',
            BASE_DIR / 'frontend' / 'dist',  # 프런트엔드 빌드 결과물
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_url = config('INTERNAL_DATABASE_URL', default='') or config('DATABASE_URL', default='')
if not db_url:
    db_url = f'sqlite:///{BASE_DIR / "db.sqlite3"}'

DATABASES = {
    'default': dj_database_url.parse(
        db_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files locations (frontend build output)
STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend' / 'dist',  # 프론트엔드 빌드 결과물
]

# Cloudinary 설정
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

cloudinary_logger = logging.getLogger('django')

# Render 등 일부 환경에서는 CLOUDINARY_URL만 제공될 수 있으므로 파싱해서 보조값으로 사용한다.
cloudinary_url = config('CLOUDINARY_URL', default='')
if cloudinary_url and (
    not CLOUDINARY_STORAGE['CLOUD_NAME']
    or not CLOUDINARY_STORAGE['API_KEY']
    or not CLOUDINARY_STORAGE['API_SECRET']
):
    try:
        parsed_url = urlparse(cloudinary_url)
        fallback_cloud_name = parsed_url.hostname or ''
        fallback_api_key = parsed_url.username or ''
        fallback_api_secret = parsed_url.password or ''
    except ValueError:
        cloudinary_logger.warning('Invalid CLOUDINARY_URL format. Skipping fallback parsing.')
    else:
        if not CLOUDINARY_STORAGE['CLOUD_NAME'] and fallback_cloud_name:
            CLOUDINARY_STORAGE['CLOUD_NAME'] = fallback_cloud_name
        if not CLOUDINARY_STORAGE['API_KEY'] and fallback_api_key:
            CLOUDINARY_STORAGE['API_KEY'] = fallback_api_key
        if not CLOUDINARY_STORAGE['API_SECRET'] and fallback_api_secret:
            CLOUDINARY_STORAGE['API_SECRET'] = fallback_api_secret
        cloudinary_logger.info('Cloudinary credentials populated from CLOUDINARY_URL fallback.')

# Cloudinary 라이브러리 직접 설정
if all(
    [
        CLOUDINARY_STORAGE['CLOUD_NAME'],
        CLOUDINARY_STORAGE['API_KEY'],
        CLOUDINARY_STORAGE['API_SECRET'],
    ]
):
    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
        api_key=CLOUDINARY_STORAGE['API_KEY'],
        api_secret=CLOUDINARY_STORAGE['API_SECRET'],
        secure=True,
    )
else:
    cloudinary_logger.warning(
        'Cloudinary credentials are incomplete. Upload features will fail until they are provided.'
    )

# Media files (User uploaded files) - Cloudinary 사용
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MES_API_BASE = os.getenv('MES_API_BASE', 'https://v3-ali.blacklake.cn/api/openapi/domain/web/v1/route')
MES_ACCESS_TOKEN = os.getenv('MES_ACCESS_TOKEN', '')

AI_WORKER_TOKEN = os.getenv('AI_WORKER_TOKEN', '')
AI_JOB_CLAIM_LIMIT = int(os.getenv('AI_JOB_CLAIM_LIMIT', '1') or 1)
AI_JOB_TIMEOUT_SECONDS = int(os.getenv('AI_JOB_TIMEOUT_SECONDS', '600') or 600)


from datetime import timedelta

# ... (other imports)

# Simple JWT 설정
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "LEEWAY": 30,
}


# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {'oauth_query': {'()': 'mes_oauth.security.OAuthQueryLogFilter'}},
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['oauth_query'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'injection': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# MES API 설정
MES_API_BASE = os.getenv('MES_API_BASE', 'https://v3-ali.blacklake.cn/api/openapi/domain/web/v1/route')
MES_API_TOKEN = os.getenv('MES_API_TOKEN', '')

# Celery 설정
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = False

# Celery Beat 스케줄러 설정 (django-celery-beat 사용 시)
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# First-password activation only; no actual actor IDs or role grants in source.
ACCOUNT_ACTIVATION_APPROVED_TARGETS = config('ACCOUNT_ACTIVATION_APPROVED_TARGETS', default='{}')
ACCOUNT_ACTIVATION_ORIGIN = 'https://wj-reporting-backend.onrender.com'

# Role admission is independent of self-set password activation.
INSPECTION_PILOT_ENABLED = config('INSPECTION_PILOT_ENABLED', default=False, cast=bool)
INSPECTION_PILOT_USER_IDS = config('INSPECTION_PILOT_USER_IDS', default='[]')

# Identity verification only. Activation/deployment/app grants are separately approved.
MES_USER_OAUTH_ENABLED = config('MES_USER_OAUTH_ENABLED', default=False, cast=bool)
MES_USER_OAUTH_CALLBACK_ORIGIN = 'https://wj-reporting-backend.onrender.com'
MES_USER_OAUTH_PROVIDER_ORIGIN = 'https://v3-ali.blacklake.cn'
MES_USER_OAUTH_LAUNCH_URL = config('MES_USER_OAUTH_LAUNCH_URL', default='')
MES_USER_OAUTH_REVIEW_REFERENCE = config('MES_USER_OAUTH_REVIEW_REFERENCE', default='')
MES_USER_OAUTH_USER_MAP = config('MES_USER_OAUTH_USER_MAP', default='{}')
MES_USER_OAUTH_LOGIN_FACTORY_NUMBER = config('MES_USER_OAUTH_LOGIN_FACTORY_NUMBER', default='')
MES_USER_OAUTH_LOGIN_HINTS = config('MES_USER_OAUTH_LOGIN_HINTS', default='{}')
MES_USER_OAUTH_APP_ACCESS_TOKEN = config('MES_USER_OAUTH_APP_ACCESS_TOKEN', default='')
# Server issuance stays opt-in; no fallback to inventory credentials.
MES_USER_OAUTH_APP_TOKEN_SOURCE = config('MES_USER_OAUTH_APP_TOKEN_SOURCE', default='static')
MES_USER_OAUTH_APP_CREDENTIAL_SOURCE = config('MES_USER_OAUTH_APP_CREDENTIAL_SOURCE', default='dedicated')
MES_USER_OAUTH_APP_TOKEN_HEADER = config('MES_USER_OAUTH_APP_TOKEN_HEADER', default='access_token')
MES_USER_OAUTH_APP_ID = config('MES_USER_OAUTH_APP_ID', default='')
# Optional exact QC for an app-auth read control; empty means no control call.
MES_USER_OAUTH_CONTROL_QC_ID = config('MES_USER_OAUTH_CONTROL_QC_ID', default='')
MES_USER_OAUTH_APP_KEY = config('MES_USER_OAUTH_APP_KEY', default='')
MES_USER_OAUTH_APP_SECRET = config('MES_USER_OAUTH_APP_SECRET', default='')
# Explicit existing_mes selection can read the existing server secret directly;
# it never imports the inventory helper or silently falls back to its tokens.
MES_APP_KEY = config('MES_APP_KEY', default='')
MES_APP_SECRET = config('MES_APP_SECRET', default='')
MES_INSPECTION_ENABLED = config('MES_INSPECTION_ENABLED', default=False, cast=bool)
MES_INSPECTION_CONTRACT = config('MES_INSPECTION_CONTRACT', default='')

# Local candidate only. Both gates and every contract remain unconfigured by default.
MES_USER_SESSION_BRIDGE_ENABLED = config('MES_USER_SESSION_BRIDGE_ENABLED', default=False, cast=bool)
MES_USER_TOKEN_STORAGE_ENABLED = config('MES_USER_TOKEN_STORAGE_ENABLED', default=False, cast=bool)
MES_USER_TOKEN_KEYS = config('MES_USER_TOKEN_KEYS', default='')
MES_USER_TOKEN_ACTIVE_KEY_ID = config('MES_USER_TOKEN_ACTIVE_KEY_ID', default='')
MES_USER_TOKEN_EXPIRY_MODE = config('MES_USER_TOKEN_EXPIRY_MODE', default='')
MES_USER_TOKEN_CONTRACT_REFERENCE = config('MES_USER_TOKEN_CONTRACT_REFERENCE', default='')
MES_USER_TOKEN_POLICY_REFERENCE = config('MES_USER_TOKEN_POLICY_REFERENCE', default='')
MES_USER_TOKEN_APP_ID = config('MES_USER_TOKEN_APP_ID', default='')
MES_USER_TOKEN_TENANT_REFERENCE = config('MES_USER_TOKEN_TENANT_REFERENCE', default='')
MES_USER_TOKEN_MAX_AGE_SECONDS = config('MES_USER_TOKEN_MAX_AGE_SECONDS', default=0, cast=int)
MES_USER_TOKEN_IDLE_SECONDS = config('MES_USER_TOKEN_IDLE_SECONDS', default=0, cast=int)
MES_USER_TOKEN_CONSENT_SECONDS = config('MES_USER_TOKEN_CONSENT_SECONDS', default=0, cast=int)
MES_USER_TOKEN_SAFETY_SECONDS = config('MES_USER_TOKEN_SAFETY_SECONDS', default=30, cast=int)
MES_USER_FRONTEND_ORIGIN = 'https://wj-reporting.onrender.com'
