# Generated by Django 5.2.3 on 2025-09-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_dt', models.DateTimeField(verbose_name='보고일시')),
                ('section', models.CharField(choices=[('LQC_INJ', 'LQC_INJ'), ('LQC_ASM', 'LQC_ASM'), ('IQC', 'IQC'), ('OQC', 'OQC'), ('CS', 'CS')], default='LQC_INJ', max_length=16, verbose_name='보고부문')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='모델')),
                ('part_no', models.CharField(blank=True, default='', max_length=64, verbose_name='파트넘버')),
                ('lot_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='LOT 수')),
                ('inspection_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='검사수')),
                ('defect_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='불량수')),
                ('defect_rate', models.CharField(blank=True, default='', max_length=16, verbose_name='불량률')),
                ('judgement', models.CharField(default='NG', max_length=8, verbose_name='판정결과')),
                ('phenomenon', models.TextField(blank=True, default='', verbose_name='불량 현상')),
                ('disposition', models.TextField(blank=True, default='', verbose_name='처리 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_dt', '-id'],
            },
        ),
    ]
