# Generated by Django 5.2.3 on 2025-10-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quality_reports/', verbose_name='불량 이미지'),
        ),
    ]
