# Generated by Django 5.2.3 on 2025-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_qualityreport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityreport',
            name='image',
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='quality_reports/', verbose_name='불량 이미지 1'),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='quality_reports/', verbose_name='불량 이미지 2'),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='quality_reports/', verbose_name='불량 이미지 3'),
        ),
    ]
