# Generated by Django 5.2.3 on 2025-10-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_remove_qualityreport_image_qualityreport_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreport',
            name='image1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='불량 이미지 1'),
        ),
        migrations.AlterField(
            model_name='qualityreport',
            name='image2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='불량 이미지 2'),
        ),
        migrations.AlterField(
            model_name='qualityreport',
            name='image3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='불량 이미지 3'),
        ),
    ]
