# Generated by Django 5.2.3 on 2026-08-18 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_qualityimportbatch_qualityimportasset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityimportbatch',
            name='import_scope_key',
            field=models.CharField(db_index=True, default='full', max_length=32),
        ),
        migrations.AlterField(
            model_name='qualityimportbatch',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='qualityimportprovenance',
            name='source_sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='qualityimportbatch',
            constraint=models.UniqueConstraint(fields=('sha256', 'import_scope_key'), name='quality_import_unique_source_scope'),
        ),
    ]
