# Generated by Django 5.2.3 on 2026-09-30 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_qualityreport_direct_excel_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(editable=False, max_length=64, unique=True)),
                ('source_kind', models.CharField(default='local_manual', editable=False, max_length=24)),
                ('work_order_ref', models.CharField(max_length=128)),
                ('task_ref', models.CharField(max_length=128)),
                ('part_no', models.CharField(max_length=128)),
                ('equipment_ref', models.CharField(max_length=128)),
                ('inspection_type', models.CharField(default='first', max_length=16)),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(max_length=32)),
                ('warehouse_ref', models.CharField(max_length=128)),
                ('lot_ref', models.CharField(max_length=128)),
                ('work_started_at', models.DateTimeField()),
                ('inspection_items', models.JSONField(default=list)),
                ('require_evidence', models.BooleanField(default=False)),
                ('quantity_mode', models.CharField(default='recorded', max_length=16)),
                ('judgement_policy', models.CharField(default='strict_items', max_length=16)),
                ('assigned_to_name', models.CharField(max_length=150)),
                ('status', models.CharField(db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('measurements', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('inspected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('judgement', models.CharField(blank=True, default='', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('review_reason', models.CharField(blank=True, default='', max_length=500)),
                ('sync_status', models.CharField(default='not_synced', max_length=16)),
                ('mes_completion_status', models.CharField(default='not_completed', max_length=24)),
                ('injection_receipt_readiness', models.CharField(default='not_verified', max_length=16)),
                ('mes_snapshot', models.JSONField(default=dict)),
                ('mes_checked_at', models.DateTimeField(null=True)),
                ('external_result_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reinspection', to='quality.inspectionrequest')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inspections', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('manage_inspectionrequest', 'Create and edit local inspection requests'), ('submit_inspectionrequest', 'Submit inspection results'), ('review_inspectionrequest', 'Independently review inspection results')],
            },
        ),
        migrations.CreateModel(
            name='InspectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('result_digest', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='quality.inspectionrequest')),
            ],
            options={
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InspectionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=128)),
                ('key', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(default=202)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='quality.inspectionrequest')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='quality_inspection_operation_key')],
            },
        ),
    ]
