# Generated by Django 5.2.3 on 2026-10-03 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_inspection_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionMesBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=128)),
                ('qc_id', models.CharField(max_length=19)),
                ('work_order_id', models.CharField(max_length=19)),
                ('contract', models.JSONField(default=dict)),
                ('reviewed_result_digest', models.CharField(max_length=64)),
                ('test_only', models.BooleanField(default=False)),
                ('test_label', models.CharField(max_length=500)),
                ('phase', models.CharField(default='ready', max_length=24)),
                ('evidence_digest', models.CharField(blank=True, default='', max_length=64)),
                ('last_verified_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mes_binding', to='quality.inspectionrequest')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'qc_id'), name='quality_mes_binding_target')],
            },
        ),
    ]
