# Generated by Django 5.2.3 on 2026-10-03 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_inspection_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionNonconformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='open', max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, null=True)),
                ('uom', models.CharField(max_length=32)),
                ('owner_name', models.CharField(max_length=150)),
                ('defect_types', models.JSONField(default=list)),
                ('cause', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(default=list)),
                ('original_result_digest', models.CharField(max_length=64)),
                ('mes_status', models.CharField(default='unverified', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformance', to='quality.inspectionrequest')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
