# Generated by Django 5.2.3 on 2026-10-07 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_inspection_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionShiftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('starts_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appearance_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearance_inspection_shifts', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_shifts', to=settings.AUTH_USER_MODEL)),
                ('dimension_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimension_inspection_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InspectionRoleWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_snapshot', models.JSONField(default=dict)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('item_areas', models.JSONField(default=dict)),
                ('status', models.CharField(default='unconfigured', max_length=24)),
                ('new_role_only', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='role_workflow', to='quality.inspectionrequest')),
                ('shift_setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='quality.inspectionshiftsetting')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InspectionAreaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('appearance', 'Appearance'), ('dimension', 'Dimension')], max_length=16)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('judgement', models.CharField(blank=True, default='', max_length=8)),
                ('measurements', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('completed_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('completed_at', models.DateTimeField(null=True)),
                ('mes_status', models.CharField(default='blocked', max_length=24)),
                ('mes_blocked_reason', models.CharField(default='mes_partial_multi_executor_contract_unverified', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspection_areas', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_inspection_areas', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='quality.inspectionroleworkflow')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('workflow', 'area'), name='quality_inspection_role_area')],
            },
        ),
    ]
