# Generated by Django 5.2.3 on 2026-10-03 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_inspection_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionOAuthAttempt',
            fields=[
                ('nonce_digest', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(editable=False, max_length=64)),
                ('policy_digest', models.CharField(editable=False, max_length=64)),
                ('code_digest', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('expected_user_id', models.CharField(editable=False, max_length=19)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
