# Generated by Django 5.2.3 on 2026-10-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_inspection_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionshiftsetting',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionshiftsetting',
            name='effective_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
