# Generated by Django 5.2.3 on 2026-10-07 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_inspection_shift_effective_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionarearesult',
            name='completed_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_completed_inspection_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionarearesult',
            name='completed_recorded_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='inspectionarearesult',
            name='item_authorship',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inspectionroleworkflow',
            name='shared_terminal_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_terminal_inspection_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionroleworkflow',
            name='shared_terminal_operator_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
