# Generated by Django 5.2.3 on 2026-10-07 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0016_inspection_final_concession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=384)),
                ('distinguishing_note', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_note', models.CharField(blank=True, default='', max_length=192)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_inspectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='inspectionarearesult',
            name='assigned_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_areas', to='quality.inspectioninspector'),
        ),
        migrations.AddField(
            model_name='inspectionarearesult',
            name='completed_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_areas', to='quality.inspectioninspector'),
        ),
        migrations.AddField(
            model_name='inspectionshiftsetting',
            name='appearance_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appearance_shifts', to='quality.inspectioninspector'),
        ),
        migrations.AddField(
            model_name='inspectionshiftsetting',
            name='dimension_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dimension_shifts', to='quality.inspectioninspector'),
        ),
        migrations.CreateModel(
            name='InspectionWeeklyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_weeks', to=settings.AUTH_USER_MODEL)),
                ('day_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_weeks', to='quality.inspectionshiftsetting')),
                ('night_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='night_weeks', to='quality.inspectionshiftsetting')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start'],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='inspectioninspector',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'normalized_note'), name='quality_inspector_normalized_name_note'),
        ),
    ]
