# Generated by Django 5.2.3 on 2026-10-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_alter_aijob_job_type'),
        ('quality', '0017_inspection_weekly_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityActionResultTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sha256', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('prompt_version', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_core.aijob')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_result_translation', to='quality.qualityreport')),
            ],
        ),
    ]
