# Generated by Django 5.2.3 on 2026-09-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_zh', models.CharField(blank=True, default='', max_length=200)),
                ('objective', models.TextField()),
                ('phase', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.CharField(default='P1', max_length=2)),
                ('status', models.CharField(db_index=True, default='planned', max_length=20)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('dependencies', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('checklist', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list)),
                ('completion_note', models.TextField(blank=True, default='')),
                ('verification_note', models.TextField(blank=True, default='')),
                ('release_state', models.CharField(default='unreleased', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('changed_fields', models.JSONField(default=list)),
                ('change_note', models.TextField(blank=True, default='')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='analytics.developmenttask')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
