# Generated by Django 5.2.3 on 2026-10-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_hr_monthly_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrClassificationReference',
            fields=[
                ('key', models.CharField(default='company', max_length=20, primary_key=True, serialize=False)),
                ('reference', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HrClassificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor_label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='analytics.hrclassificationreference')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hrclassificationreference',
            constraint=models.CheckConstraint(condition=models.Q(('key', 'company')), name='hr_reference_company_only'),
        ),
        migrations.AddConstraint(
            model_name='hrclassificationhistory',
            constraint=models.UniqueConstraint(fields=('reference', 'version'), name='hr_reference_history_version'),
        ),
    ]
