# Generated by Django 5.2.3 on 2025-08-19 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyPartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, unique=True, verbose_name='Part No')),
                ('model_code', models.CharField(max_length=100, verbose_name='모델 코드')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('process_type', models.CharField(blank=True, max_length=50, verbose_name='가공 타입')),
                ('material_type', models.CharField(blank=True, max_length=50, verbose_name='소재 종류')),
                ('standard_cycle_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='표준 사이클 타임(분)')),
                ('standard_worker_count', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='표준 작업자수')),
                ('valid_from', models.DateField(verbose_name='유효 시작일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '가공 품목 스펙',
                'verbose_name_plural': '가공 품목 스펙 목록',
                'ordering': ['part_no', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='생산일자')),
                ('line_no', models.CharField(blank=True, max_length=20, verbose_name='라인번호')),
                ('part_no', models.CharField(max_length=100, verbose_name='Part No.')),
                ('model', models.CharField(max_length=50, verbose_name='모델명')),
                ('plan_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='계획수량')),
                ('actual_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='실제수량')),
                ('incoming_defect', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='来料不良')),
                ('injection_outsourcing_defect', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='注塑/外协불량')),
                ('processing_defect', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='加工不良')),
                ('operation_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가동시간(분)')),
                ('total_time', models.IntegerField(default=1440, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총시간(분)')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '가공 보고서',
                'verbose_name_plural': '가공 보고서 목록',
                'ordering': ['-date', 'line_no', 'model'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='모델명')),
                ('part_no', models.CharField(max_length=100, verbose_name='대표 PART-NO')),
                ('process_line', models.CharField(blank=True, max_length=50, verbose_name='가공 라인')),
            ],
            options={
                'verbose_name': '가공 제품',
                'verbose_name_plural': '가공 제품 목록',
                'ordering': ['model', 'part_no'],
                'unique_together': {('model', 'part_no')},
            },
        ),
    ]
