# Generated by Django 5.2.3 on 2025-08-19 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyreport',
            name='incoming_defect',
        ),
        migrations.RemoveField(
            model_name='assemblyreport',
            name='injection_outsourcing_defect',
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='injection_defect',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='注塑不良'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='outsourcing_defect',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='外协不良'),
        ),
    ]
