# Generated by Django 5.2.3 on 2025-08-19 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_remove_assemblyreport_incoming_defect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyreport',
            name='idle_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부동시간(분)'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='input_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='투입수량'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='workers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='작업인원(명)'),
        ),
    ]
