# Generated by Django 5.2.3 on 2025-08-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_assemblyreport_idle_time_assemblyreport_input_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyreport',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='assemblyreport',
            name='start_datetime',
        ),
    ]
