# Generated by Django 5.2.3 on 2025-09-02 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_remove_assemblyreport_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyreport',
            name='rework_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='재작업 수량'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('JIT', 'JIT'), ('CSK', 'CSK'), ('SVC', 'SVC')], default='', max_length=10, verbose_name='공급유형'),
        ),
    ]
