# Generated by Django 5.2.3 on 2025-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_assemblyreport_rework_qty_assemblyreport_supply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyreport',
            name='incoming_defects_detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='입고/사출 상세불량'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='processing_defects_detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='가공 상세불량'),
        ),
    ]
