# Generated by Django 5.2.3 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0006_assemblyreport_incoming_defects_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyreport',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('JIT', 'JIT'), ('CSK', 'CSK'), ('SVC', 'SVC'), ('REWORK', 'REWORK')], default='', max_length=10, verbose_name='공급유형'),
        ),
    ]
