# Generated by Django 5.2.3 on 2025-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_alter_assemblyreport_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyreport',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('JIT', 'JIT'), ('CSK', 'CSK'), ('SVC', 'SVC'), ('REWORK', 'REWORK'), ('INSPECTION', 'INSPECTION')], default='JIT', max_length=10, verbose_name='공급유형'),
        ),
    ]
