# Generated by Django 5.2.3 on 2025-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0009_alter_assemblyreport_supply_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('processing', '가공불량'), ('outsourcing', '외주불량')], max_length=20, verbose_name='불량 카테고리')),
                ('defect_type', models.CharField(max_length=100, verbose_name='불량 유형')),
                ('usage_count', models.IntegerField(default=1, verbose_name='사용 횟수')),
                ('first_used', models.DateTimeField(auto_now_add=True, verbose_name='최초 사용일')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='최종 사용일')),
            ],
            options={
                'verbose_name': '불량 히스토리',
                'verbose_name_plural': '불량 히스토리 목록',
                'ordering': ['-last_used', '-usage_count'],
            },
        ),
        migrations.DeleteModel(
            name='AssemblyPartSpec',
        ),
        migrations.DeleteModel(
            name='AssemblyProduct',
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='outsourcing_defects_dynamic',
            field=models.JSONField(blank=True, default=list, help_text="[{'type': '치수불량', 'quantity': 3, 'timestamp': '...'}, ...]", verbose_name='외주불량 동적 리스트'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='processing_defects_dynamic',
            field=models.JSONField(blank=True, default=list, help_text="[{'type': '스크래치', 'quantity': 5, 'timestamp': '...'}, ...]", verbose_name='가공불량 동적 리스트'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['category', '-last_used'], name='assembly_de_categor_9aed91_idx'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['category', '-usage_count'], name='assembly_de_categor_89a84f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='defecthistory',
            unique_together={('category', 'defect_type')},
        ),
    ]
