# Generated by Django 5.2.3 on 2026-05-18 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('production_daily_analysis', 'Production Daily Analysis'), ('production_machine_analysis', 'Production Machine Analysis'), ('quality_image_analysis', 'Quality Image Analysis')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('claimed_by', models.CharField(blank=True, default='', max_length=128)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_core_aij_status_59b752_idx'), models.Index(fields=['job_type', 'status', 'created_at'], name='ai_core_aij_job_typ_f5b799_idx'), models.Index(fields=['created_by', '-created_at'], name='ai_core_aij_created_95cdcf_idx')],
            },
        ),
    ]
