# Generated by Django 5.2.3 on 2026-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='job_type',
            field=models.CharField(choices=[('production_daily_analysis', 'Production Daily Analysis'), ('production_machine_analysis', 'Production Machine Analysis'), ('quality_image_analysis', 'Quality Image Analysis'), ('deep_analysis', 'Deep Analysis')], db_index=True, max_length=64),
        ),
    ]
