# Generated by Django 5.2.3 on 2026-10-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_deep_analysis_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='job_type',
            field=models.CharField(choices=[('production_daily_analysis', 'Production Daily Analysis'), ('production_machine_analysis', 'Production Machine Analysis'), ('quality_image_analysis', 'Quality Image Analysis'), ('deep_analysis', 'Deep Analysis'), ('quality_action_result_translation', 'Quality Action Result Translation')], db_index=True, max_length=64),
        ),
    ]
