# Generated by Django 5.2.3 on 2025-07-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactInventory',
            fields=[
                ('qr_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('material_id', models.BigIntegerField()),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('biz_type', models.CharField(blank=True, max_length=50)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('warehouse_name', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('storage_status', models.CharField(blank=True, max_length=50)),
                ('qc_status', models.CharField(blank=True, max_length=50)),
                ('work_order_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse_code'], name='inventory_f_warehou_5019fe_idx'), models.Index(fields=['material_code'], name='inventory_f_materia_51db5d_idx'), models.Index(fields=['qr_code'], name='inventory_f_qr_code_9bffbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StagingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.BigIntegerField()),
                ('material_code', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('biz_type', models.CharField(blank=True, max_length=50)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('warehouse_name', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('storage_status', models.CharField(blank=True, max_length=50)),
                ('qc_status', models.CharField(blank=True, max_length=50)),
                ('work_order_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['fetched_at'], name='inventory_s_fetched_a53d73_idx'), models.Index(fields=['material_code'], name='inventory_s_materia_e6b114_idx')],
            },
        ),
    ]
