# Generated by Django 5.2.3 on 2025-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staginginventory',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
