# Generated by Django 5.2.3 on 2025-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_staginginventory_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='factinventory',
            name='label_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staginginventory',
            name='label_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='factinventory',
            index=models.Index(fields=['label_code'], name='inventory_f_label_c_5bc7f3_idx'),
        ),
    ]
