# Generated by Django 5.2.3 on 2025-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_composite_key'),
        ('inventory', '0003_factinventory_label_code_staginginventory_label_code_and_more'),
    ]

    operations = [
    ]
