# Generated by Django 5.2.3 on 2025-07-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_20250731_0805'),
    ]

    operations = [
        # 1. 먼저 qr_code를 primary key에서 제거
        migrations.AlterField(
            model_name='factinventory',
            name='qr_code',
            field=models.CharField(max_length=100),
        ),
        # 2. 새로운 id 필드 추가
        migrations.AddField(
            model_name='factinventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factinventory',
            name='composite_key',
            field=models.CharField(default='', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='staginginventory',
            name='composite_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=220, null=True),
        ),
        migrations.AddIndex(
            model_name='factinventory',
            index=models.Index(fields=['composite_key'], name='inventory_f_composi_3db09a_idx'),
        ),
    ]
