# Generated by Django 5.2.3 on 2025-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_factinventory_id_alter_factinventory_composite_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factinventory',
            name='is_duplicate_suspicious',
            field=models.BooleanField(default=False, help_text='중복 의심 데이터 여부'),
        ),
    ]
