# Generated by Django 5.2.3 on 2025-07-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_factinventory_is_duplicate_suspicious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factinventory',
            name='is_duplicate_suspicious',
        ),
    ]
