# Generated by Django 5.2.3 on 2025-07-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_factinventory_is_duplicate_suspicious'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('warehouse_code', models.CharField(db_index=True, max_length=50)),
                ('warehouse_name', models.CharField(blank=True, max_length=255)),
                ('qc_status', models.CharField(blank=True, max_length=50)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('cart_count', models.IntegerField(default=0)),
                ('cart_details', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_date', 'material_code'], name='inventory_d_snapsho_82336f_idx'), models.Index(fields=['snapshot_date', 'warehouse_code'], name='inventory_d_snapsho_5fb992_idx'), models.Index(fields=['material_code', 'warehouse_code'], name='inventory_d_materia_c5016c_idx')],
                'unique_together': {('snapshot_date', 'material_code', 'warehouse_code', 'qc_status')},
            },
        ),
    ]
