# Generated by Django 5.2.3 on 2025-08-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_dailyinventorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('total_items', models.IntegerField(default=0)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_carts', models.IntegerField(default=0)),
                ('warehouse_summary', models.JSONField(default=dict)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyinventorysnapshot',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyinventorysnapshot',
            name='excel_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dailyinventorysnapshot',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyinventorysnapshot',
            name='total_carts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyinventorysnapshot',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='dailyinventorysnapshot',
            index=models.Index(fields=['snapshot_date', 'is_email_sent'], name='inventory_d_snapsho_72b15f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportsummary',
            index=models.Index(fields=['snapshot_date'], name='inventory_d_snapsho_a878df_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportsummary',
            index=models.Index(fields=['is_email_sent'], name='inventory_d_is_emai_3be4bb_idx'),
        ),
    ]
