# Generated by Django 5.2.3 on 2025-08-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_dailyreportsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportsummary',
            name='email_recipients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailyreportsummary',
            name='email_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportsummary',
            name='email_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dailyreportsummary',
            index=models.Index(fields=['email_status'], name='inventory_d_email_s_495043_idx'),
        ),
    ]
