# Generated by Django 5.2.3 on 2025-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_dailyreportsummary_email_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedPartSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, unique=True, verbose_name='Part No')),
                ('model_code', models.CharField(max_length=100, verbose_name='모델 코드')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('valid_from', models.DateField(verbose_name='유효 시작일')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='색상')),
                ('mold_type', models.CharField(blank=True, max_length=50, verbose_name='금형 타입')),
                ('resin_type', models.CharField(blank=True, max_length=50, verbose_name='Resin 종류')),
                ('resin_code', models.CharField(blank=True, max_length=50, verbose_name='Resin 코드')),
                ('net_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Net 중량(g)')),
                ('sr_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='S/R 중량(g)')),
                ('cycle_time_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='사이클 타임(초)')),
                ('cavity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cavity')),
                ('tonnage', models.PositiveIntegerField(blank=True, null=True, verbose_name='형체력(T)')),
                ('efficiency_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='효율(%)')),
                ('resin_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resin Loss(%)')),
                ('defect_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='불량률(%)')),
                ('process_type', models.CharField(blank=True, max_length=50, verbose_name='가공 타입')),
                ('material_type', models.CharField(blank=True, max_length=50, verbose_name='소재 종류')),
                ('standard_cycle_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='표준 사이클 타임(분)')),
                ('standard_worker_count', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='표준 작업자수')),
                ('source_system', models.CharField(choices=[('injection', '사출'), ('assembly', '가공'), ('quality', '품질'), ('unified', '통합')], default='unified', max_length=20, verbose_name='생성 시스템')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '통합 품목 스펙',
                'verbose_name_plural': '통합 품목 스펙 목록',
                'ordering': ['part_no', '-valid_from'],
                'indexes': [models.Index(fields=['part_no'], name='inventory_u_part_no_7ab672_idx'), models.Index(fields=['model_code'], name='inventory_u_model_c_76cb7b_idx'), models.Index(fields=['part_no', 'model_code'], name='inventory_u_part_no_1faca4_idx'), models.Index(fields=['valid_from'], name='inventory_u_valid_f_fdfac2_idx'), models.Index(fields=['is_active'], name='inventory_u_is_acti_02a8be_idx')],
            },
        ),
    ]
