"""Initial development plan; code availability and business acceptance are separate.

Roles are suggestions, not assigned people. Existing screen/code references do
not assert that a planned objective has been implemented or deployed. This
catalog does not authorize collection, schema changes, or production changes.
"""

CATALOG_VERSION = '2026-09-07'

INITIAL_TASKS = [
    {
        'slug': 'analysis-baseline',
        'title': '생산·품질 분석 기반 구현 확인',
        'title_zh': '确认生产与质量分析基础功能',
        'objective': '원천 실패·미기록·정상 0을 구분하고 같은 날짜·설비 범위에서 생산과 품질 근거를 확인한다.',
        'phase': 0,
        'priority': 'P1',
        'status': 'review',
        'owner': '개발 / 생산관리 / 품질 (역할 제안)',
        'dependencies': [],
        'requirements': [
            {'id': 'baseline-mes', 'kind': 'mes', 'text': '기존 저장 형합 기록과 MES 보고실적을 대표 작업의 원본과 대조한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'baseline-acceptance', 'kind': 'human', 'text': '대표 생산 작업과 품질 신고를 골라 화면·원본·CSV를 대조한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'baseline-owner', 'kind': 'decision', 'text': '생산 및 품질 업무 인수 담당을 지정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'baseline-source-state', 'text': '실제 업무 사례에서 원천 실패와 정상 0·미기록이 구분되는지 확인한다.', 'done': False},
            {'id': 'baseline-scope', 'text': '선택한 날짜·설비 범위가 화면 이동과 CSV에 유지되는지 확인한다.', 'done': False},
            {'id': 'baseline-quality', 'text': 'Pareto·모델 연결·건/시프트의 의미와 원본 연결을 품질 담당자가 확인한다.', 'done': False},
            {'id': 'baseline-release', 'text': '코드 반영·서비스 버전·현장 인수 결과를 각각 기록한다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/injection/dashboard', 'label': '기존 참고 · 사출 실적과 원천 확인'},
            {'kind': 'screen', 'url': '/quality/analysis', 'label': '기존 참고 · 품질 Pareto·모델 연결·시프트 신고 빈도'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/frontend/src/domains/injection/InjectionEvidencePanel.tsx', 'label': '기존 참고 · 사출 원천 패널 코드'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/production_context.py', 'label': '기존 참고 · 품질 생산 후보 연결 코드'},
            {'kind': 'doc', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/docs/reviews/2026-09-07-quality-production-context.md', 'label': '기존 참고 · 품질 생산 연결 검증 기록'},
        ],
        'completion_note': '기준 main 4e58afff에 기반 기능이 구현되어 있다. 현장 인수 완료와 서비스 반영 확인은 별도로 기록한다.',
        'verification_note': '기존 문서에 품질·사출 회귀와 합성 화면 검증 기록이 있다. 이 카탈로그의 체크리스트는 코드 존재만으로 완료 처리하지 않았다.',
        'release_state': 'code_available',
        'sort_order': 10,
    },
    {
        'slug': 'quality-trend-retained-dates',
        'title': '품질 추세에 남은 날짜의 근거 표시',
        'title_zh': '显示质量趋势保留日期的依据',
        'objective': '접은 날짜와 근거 부족으로 유지한 날짜를 사용자가 구분한다. 일요일·공휴일·신고 0건만으로 무생산을 확정하지 않는다.',
        'phase': 0,
        'priority': 'P1',
        'status': 'review',
        'owner': '개발 / 품질 (역할 제안)',
        'dependencies': ['analysis-baseline'],
        'requirements': [
            {'id': 'trend-calendar', 'kind': 'mes', 'text': '기존 activity_calendar의 판정 사유와 관측 설비 수를 실제 조회 범위에서 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'trend-dates', 'kind': 'human', 'text': '2026-08-16·08-23의 실제 API 판정과 업무 해석을 확인한다. 근거가 부족하면 날짜를 유지한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'trend-release', 'kind': 'decision', 'text': '별도 작업 트리의 변경을 검토하고 통합 및 서비스 반영 범위를 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'trend-reasons', 'text': '접은 날짜 목록과 유지 사유가 선택 범위에 맞게 표시되는지 확인한다.', 'done': False},
            {'id': 'trend-originals', 'text': '원본 일별 행·CSV·기간 합계가 보존되는지 확인한다.', 'done': False},
            {'id': 'trend-failure', 'text': '보조 자료 실패 시 날짜를 임의로 제외하지 않는지 확인한다.', 'done': False},
            {'id': 'trend-handoff', 'text': '통합·서비스 반영·현장 확인 결과를 각각 기록한다.', 'done': False},
        ],
        'locations': [],
        'completion_note': 'wj_reporting-quality-trend-display 작업 트리에 로컬 변경이 있으며 현재 서버에는 미반영이다. QualityAnalysisPage.tsx·trend.ts와 검토 문서가 미커밋 상태다.',
        'verification_note': '로컬 검토 문서에는 테스트 69개·focused ESLint·빌드 및 합성 화면 검증 통과가 기록되어 있다. 운영 배포와 두 날짜의 실제 API 판정은 확인하지 않았다.',
        'release_state': 'unreleased',
        'sort_order': 20,
    },
    {
        'slug': 'observation-evidence-design',
        'title': '형합 관측 근거와 보존 범위 설계',
        'title_zh': '设计合模观测依据与保留范围',
        'objective': '원시 관측부터 압축 이후 날짜·시프트 판정까지 필요한 근거와 알 수 없는 범위를 정한다.',
        'phase': 1,
        'priority': 'P1',
        'status': 'planned',
        'owner': '개발 / 데이터 운영 / 생산관리 (역할 제안)',
        'dependencies': [],
        'requirements': [
            {'id': 'evidence-mes-fields', 'kind': 'mes', 'text': '장치·설비 식별, 원시 관측시각과 수집시각, 누적 형합수의 제공 범위와 의미를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'evidence-source-coverage', 'kind': 'mes', 'text': '조회 성공·실패 기록과 원천의 상세 자료 보존 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'evidence-machines', 'kind': 'human', 'text': '기간별 기대 설비 목록과 도입·폐기·통신 중단 이력, 대표 검증 설비와 기간을 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'evidence-retention', 'kind': 'decision', 'text': '원시 자료·관측 요약의 보존 기간, 예상 용량, 적용 범위 및 과거 자료 재평가 조건을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'evidence-cases', 'text': '미증가·증가·공백·reset·장치 변경·자정/08시 경계 사례를 정의한다.', 'done': False},
            {'id': 'evidence-contract', 'text': '첫·마지막 관측, 최대 공백, 유효 표본 수, 증가·감소/reset, 기대 설비 및 정책 버전 계약을 정리한다.', 'done': False},
            {'id': 'evidence-history', 'text': '원시 자료 또는 검증된 요약이 없는 과거 날짜의 복원 불가 범위를 명시한다.', 'done': False},
            {'id': 'evidence-lifecycle', 'text': '저장·재조회·압축 전후 비교와 실패 시 근거 보존 절차를 검토한다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/quality/analysis', 'label': '기존 참고 · 현재 날짜·시프트 표시'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/activity_calendar.py', 'label': '기존 참고 · 현행 달력일 판정 기준'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/injection/mes_service.py', 'label': '기존 참고 · 현행 수집·압축 경로'},
        ],
        'completion_note': '',
        'verification_note': '보존 계약은 아직 미구현이다. 기본 상세 보관 168시간 이후 시간별 압축 경로가 존재하며, 압축 자료만으로 연속 미증가를 확정하지 않는다.',
        'release_state': 'unreleased',
        'sort_order': 30,
    },
    {
        'slug': 'observation-evidence-preservation',
        'title': '로그 압축 전 관측 근거 보존',
        'title_zh': '在日志压缩前保留观测依据',
        'objective': '상세 로그 보존 기간이 지나도 같은 근거로 날짜와 시프트를 판정한다.',
        'phase': 1,
        'priority': 'P1',
        'status': 'planned',
        'owner': '개발 / 데이터 운영 (역할 제안)',
        'dependencies': ['observation-evidence-design'],
        'requirements': [
            {'id': 'preserve-raw', 'kind': 'mes', 'text': '검증된 원시 형합 관측 구간과 장치 식별 자료를 확보한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'preserve-pilot', 'kind': 'human', 'text': '제한된 사출 대상의 실제 관측·현장 확인 사례를 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'preserve-storage', 'kind': 'decision', 'text': '저장 구조·마이그레이션·운영 적용을 별도로 검토한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'preserve-failure', 'kind': 'decision', 'text': '보존 실패 시 압축 보류·재처리 범위와 되돌릴 절차를 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'preserve-equivalence', 'text': '원시 관측이 유효한 구간에서 압축 전후 판정이 같다.', 'done': False},
            {'id': 'preserve-safe-order', 'text': '요약 보존 실패 시 필요한 원시 근거가 먼저 삭제되지 않는다.', 'done': False},
            {'id': 'preserve-history', 'text': '신규 보존 대상과 검증 가능한 과거 재평가 대상을 구분한다.', 'done': False},
            {'id': 'preserve-retrieve', 'text': '판정과 정책 버전·공백·장치 변경 근거를 함께 재조회하며 첫 상세 보존 기간 이후에도 검증한다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/mes/monitoring', 'label': '기존 참고 · 형합 관측 조회'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/injection/mes_service.py', 'label': '기존 참고 · 확장 검토 대상 수집·압축 경로'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/production_shifts.py', 'label': '기존 참고 · 현행 시프트 판정 소비 경로'},
        ],
        'completion_note': '',
        'verification_note': '압축 전 관측 근거 보존은 계획 단계다. 기존 rollup 0이나 시간별 동일 계수로 삭제된 원시 관측을 복원하지 않는다.',
        'release_state': 'unreleased',
        'sort_order': 40,
    },
    {
        'slug': 'mes-collection-recovery',
        'title': 'MES 수집 공백·정정·재수집 추적',
        'title_zh': '追踪 MES 采集缺口、更正与补采',
        'objective': '수집 중단과 지연 정정 뒤에도 유실·중복 및 재처리 범위를 설명한다.',
        'phase': 1,
        'priority': 'P1',
        'status': 'planned',
        'owner': '데이터 운영 / 개발 (역할 제안)',
        'dependencies': ['observation-evidence-design'],
        'requirements': [
            {'id': 'recovery-runs', 'kind': 'mes', 'text': '수집 실행별 성공 범위·실패 페이지·거절 내역의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'recovery-report-identity', 'kind': 'mes', 'text': '보고 상세 ID, 수정·취소 상태, 보고시각과 실제 생산시각의 의미를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'recovery-examples', 'kind': 'human', 'text': '지연 보고·정정·취소의 실제 업무 사례를 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'recovery-policy', 'kind': 'decision', 'text': '마지막 완전 성공 기준, 겹침 조회 범위, 승인된 조회 계약과 중복 식별 기준을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'recovery-times', 'text': '최신 자료 시각과 수집 성공 시각을 구분한다.', 'done': False},
            {'id': 'recovery-resume', 'text': '중단 후 재개와 부분 페이지 실패를 재현한다.', 'done': False},
            {'id': 'recovery-dedup', 'text': '같은 범위 재수집이 중복을 만들지 않는다.', 'done': False},
            {'id': 'recovery-corrections', 'text': '늦은 정정·취소의 적용 범위와 근거가 남는다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/production/stats', 'label': '기존 참고 · 생산 원천 대사'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/production/models.py', 'label': '기존 참고 · 저장 MES 보고 기록'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/injection/mes_service.py', 'label': '기존 참고 · 형합 수집 경로'},
        ],
        'completion_note': '',
        'verification_note': '현재 수집 코드의 존재는 운영 스케줄러 정상 실행이나 원천 자료의 완전성을 보증하지 않는다. 재개·부분 실패·정정 사례의 독립 검증이 필요하다.',
        'release_state': 'unreleased',
        'sort_order': 50,
    },
    {
        'slug': 'single-production-work-link',
        'title': '사출 한 작업의 MES·현장 기록 연결',
        'title_zh': '关联单个注塑作业的 MES 与现场记录',
        'objective': '대표 작업에서 MES 추정·신고·현장·수기의 관계를 중복 합산 없이 추적한다.',
        'phase': 2,
        'priority': 'P1',
        'status': 'planned',
        'owner': '생산관리 / 현장 / 생산기술 (역할 제안)',
        'dependencies': [],
        'requirements': [
            {'id': 'work-mes-identity', 'kind': 'mes', 'text': '설비·생산 작업·작업지시·품번·공정·수량·단위와 LOT·실제 시작/종료의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'work-change-confirmation', 'kind': 'human', 'text': '실제 모델·금형 교체 시각, 시험/양산 구분, 유효 Cavity를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'work-reconciliation', 'kind': 'human', 'text': 'MES와 현장 값이 다른 대표 작업에서 확인한 원본 근거를 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'work-unit', 'kind': 'decision', 'text': '생산 구간의 최소 단위, 공식 마감 책임자, 보고일과 생산일이 다른 기록의 귀속을 정한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'work-source-relations', 'kind': 'decision', 'text': '원본·보완·정정·취소·승인의 관계와 실제 작업 연결 기준을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'work-trace', 'text': '대표 작업 하나의 설비·품번·유효 Cavity와 각 원천을 연결한다.', 'done': False},
            {'id': 'work-handover', 'text': '모델 교체와 교대 인계에서도 같은 작업 관계가 유지된다.', 'done': False},
            {'id': 'work-retry', 'text': '재전송·지연 입력·정정이 중복 실적으로 합산되지 않는다.', 'done': False},
            {'id': 'work-field-to-admin', 'text': '현장 저장 결과를 동일 범위 관리자 조회에서 확인한다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/field/imm01', 'label': '기존 참고 · 사출 현장 입력'},
            {'kind': 'screen', 'url': '/injection/dashboard', 'label': '기존 참고 · 사출 원천별 조회'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/production/field_kanban.py', 'label': '기존 참고 · 현장 작업 조회 코드'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/frontend/src/domains/injection/InjectionEvidencePanel.tsx', 'label': '기존 참고 · 사출 원천 패널 코드'},
        ],
        'completion_note': '',
        'verification_note': 'MES 20행 편의표본에서 LOT·실제 시작/종료·공수·주문번호가 표시되지 않았다. 회사 전체 미기재로 단정하지 않고 제공 범위부터 확인한다. 화면·업무 설계는 관측 보존과 병행할 수 있다.',
        'release_state': 'unreleased',
        'sort_order': 60,
    },
    {
        'slug': 'single-exception-closure',
        'title': '대표 예외 한 종류의 확인·조치·완료',
        'title_zh': '闭环处理一种代表性异常',
        'objective': '반복 품질 또는 실적 불일치 한 종류를 담당자 확인부터 완료 근거와 재발 점검까지 연결한다.',
        'phase': 3,
        'priority': 'P1',
        'status': 'planned',
        'owner': '품질 / 반장 / 공정 책임자 (역할 제안)',
        'dependencies': [],
        'requirements': [
            {'id': 'exception-originals', 'kind': 'mes', 'text': '선택한 예외에 해당하는 작업·품질·실적의 기존 원본 연결을 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'exception-action', 'kind': 'human', 'text': '사람의 확인 내용, 담당, 기한, 조치와 완료 근거를 기록한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'exception-reopen', 'kind': 'human', 'text': '취소·재개·재발의 확인 사유와 관련 원본을 남긴다.', 'status': 'needed', 'evidence': ''},
            {'id': 'exception-policy', 'kind': 'decision', 'text': '시범 예외 종류·책임자와 해결·재발·재개의 판정 기준을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'exception-confirmation', 'text': '자동 감지와 사람 확인을 구분한다.', 'done': False},
            {'id': 'exception-trace', 'text': '담당·기한·완료 근거를 원본 상세에서 추적한다.', 'done': False},
            {'id': 'exception-no-auto-close', 'text': '완료 근거 없는 자동 종결을 하지 않는다.', 'done': False},
            {'id': 'exception-history', 'text': '취소·재발·재개 이력과 미해결 체류시간을 확인한다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/quality/daily-attention', 'label': '기존 참고 · 품질 주의 대상 확인'},
            {'kind': 'screen', 'url': '/quality/analysis', 'label': '기존 참고 · 품질 집중도 분석'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/analysis.py', 'label': '기존 참고 · 신고 분석 코드'},
        ],
        'completion_note': '',
        'verification_note': '업무 시범 설계는 생산 구간 체계 전체의 완성을 기다리지 않는다. 자동 귀속·자동 마감은 필요한 원천 근거 확보 후 적용하며, 기존 주의 화면에 전사 공통 조치 종결이 완성됐다고 보지 않는다.',
        'release_state': 'unreleased',
        'sort_order': 70,
    },
    {
        'slug': 'quality-inspection-events',
        'title': '검사 이벤트와 실제 발생 근거 정리',
        'title_zh': '明确检验事件与实际发生依据',
        'objective': '신고 빈도와 검사 성과를 구분하고 검사 분모의 중복 제거 근거를 마련한다.',
        'phase': 3,
        'priority': 'P2',
        'status': 'planned',
        'owner': '품질 / 생산관리 (역할 제안)',
        'dependencies': ['single-production-work-link'],
        'requirements': [
            {'id': 'inspection-mes-meaning', 'kind': 'mes', 'text': '품질상태·작업·품번·LOT 연결의 실제 의미와 정상 검사·재검사·정정·취소 자료의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'inspection-occurrence', 'kind': 'human', 'text': '실제 발생일시 또는 시각 미상 표시와 발생 설비를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'inspection-population-fields', 'kind': 'human', 'text': '표본/전수/재검사 구분, 검사 개체 수·불량 개체 수·재작업/폐기 처분을 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'inspection-contract', 'kind': 'decision', 'text': '검사 모집단, 사건/검사 이벤트 식별, 불량 개체와 현상 건수 및 재검사 중복 처리 기준을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'inspection-times', 'text': '보고일시와 실제 발생일시를 구분한다.', 'done': False},
            {'id': 'inspection-normal', 'text': '정상 검사 포함 여부와 검사 유형을 확인한다.', 'done': False},
            {'id': 'inspection-dedup', 'text': '같은 LOT·개체의 재검사 중복을 설명한다.', 'done': False},
            {'id': 'inspection-metric-boundary', 'text': '모집단 검증 전 건/시프트를 불량률·PPM으로 바꾸지 않는다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/quality', 'label': '기존 참고 · 품질 원장'},
            {'kind': 'screen', 'url': '/quality/analysis', 'label': '기존 참고 · 신고 분석과 생산 후보 연결'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/production_context.py', 'label': '기존 참고 · 현행 생산 후보 연결'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/quality/models.py', 'label': '기존 참고 · 품질 원장 모델'},
        ],
        'completion_note': '',
        'verification_note': '현재 품질 원장은 모든 검사를 빠짐없이 기록한 모집단과 다르다. 생산 후보 연결은 발생 설비의 확정 증명이 아니며 검사 이벤트 체계가 구현됐다는 의미도 아니다.',
        'release_state': 'unreleased',
        'sort_order': 80,
    },
    {
        'slug': 'inventory-delivery-evidence',
        'title': '한 출고 품목의 재고·생산·납기 연결',
        'title_zh': '关联单个出货品项的库存、生产与交期',
        'objective': '한 주문의 출고 위험을 가용 재고·품질 보류·생산 예정·출고 이력으로 설명한다.',
        'phase': 4,
        'priority': 'P2',
        'status': 'planned',
        'owner': '자재 / 물류 / 영업 (역할 제안)',
        'dependencies': ['single-production-work-link'],
        'requirements': [
            {'id': 'delivery-stock', 'kind': 'mes', 'text': '가용·보류·예약 재고와 단위, BOM, 확정 수요·예정입고의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'delivery-orders', 'kind': 'mes', 'text': '주문행·고객 약속 버전·분할/취소/반품·실출하 이력의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'delivery-human', 'kind': 'human', 'text': '승인된 주문·약속일 원천, 품질 보류 사유, 단위 환산 근거와 대표 출고 품목을 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'delivery-policy', 'kind': 'decision', 'text': '원약속/변경 약속 평가, 분할·취소·반품 규칙과 재고 이력 보존 기간을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'delivery-reconcile', 'text': '한 품목의 주문 잔량·가용 재고·보류·예정 생산·출고를 대사한다.', 'done': False},
            {'id': 'delivery-units', 'text': '개·박스·kg 등의 단위를 환산 근거 없이 합산하지 않는다.', 'done': False},
            {'id': 'delivery-times', 'text': '재고 업무 날짜와 실제 관측 시각을 구분한다.', 'done': False},
            {'id': 'delivery-history', 'text': '원천 없는 과거 재고를 현재 값으로 채우지 않는다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/sales/inventory-status', 'label': '기존 참고 · 현재고 조회'},
            {'kind': 'screen', 'url': '/sales/raw-materials', 'label': '기존 참고 · 원자재 관리'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/inventory/views.py', 'label': '기존 참고 · 재고 조회 코드'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/inventory/services/raw_materials.py', 'label': '기존 참고 · 원자재 조회 코드'},
        ],
        'completion_note': '',
        'verification_note': '재고·물류 기존 코드의 존재와 MES 세부 자료 충실도는 별개다. 수요·예약·예정입고·고객 약속 이력이 검증되기 전 재고일수·품절 예상일·OTIF를 확정 지표로 만들지 않는다.',
        'release_state': 'unreleased',
        'sort_order': 90,
    },
    {
        'slug': 'effective-efficiency-cost',
        'title': '유효기간이 있는 생산 효율·비용 근거',
        'title_zh': '建立带有效期的生产效率与成本依据',
        'objective': '동일 생산 조건·기간·단위에서 효율과 비용을 비교할 수 있는 근거를 마련한다.',
        'phase': 5,
        'priority': 'P3',
        'status': 'planned',
        'owner': '생산기술 / 재무 / 자재 (역할 제안)',
        'dependencies': ['observation-evidence-preservation', 'single-production-work-link', 'quality-inspection-events'],
        'requirements': [
            {'id': 'efficiency-observations', 'kind': 'mes', 'text': '동시 관측 전력·형합·생산 구간과 실제 공수·자재 사용·폐기/재작업 처분의 제공 범위를 확인한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'efficiency-effective-values', 'kind': 'human', 'text': '금형·Cavity·표준 C/T 변경의 적용 시작·종료와 검증된 예정 가동시간을 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'efficiency-cost-inputs', 'kind': 'human', 'text': '재료 단가·요율·통화·유효일과 비용 대사 근거를 취합한다.', 'status': 'needed', 'evidence': ''},
            {'id': 'efficiency-policy', 'kind': 'decision', 'text': '같은 조건의 비교 범위, 재무 마감 기준 및 OEE 구성 요소의 검증 기준을 정한다.', 'status': 'needed', 'evidence': ''},
        ],
        'checklist': [
            {'id': 'efficiency-history', 'text': '현재 기준값을 과거 작업에 일괄 소급하지 않는다.', 'done': False},
            {'id': 'efficiency-scope', 'text': '형합·전력의 동일 관측 범위와 생산 조건을 확인한다.', 'done': False},
            {'id': 'efficiency-reconcile', 'text': '원가의 단위·통화·유효일·처분 근거를 대사한다.', 'done': False},
            {'id': 'efficiency-claims', 'text': '근거 확보 전 OEE·손실 금액·절감률을 성과로 제시하지 않는다.', 'done': False},
        ],
        'locations': [
            {'kind': 'screen', 'url': '/mes/monitoring', 'label': '기존 참고 · 형합·전력 계측'},
            {'kind': 'screen', 'url': '/injection/dashboard#cycle-time', 'label': '기존 참고 · C/T 확인'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/injection/mes_service.py', 'label': '기존 참고 · 계측 원천 조회 코드'},
            {'kind': 'code', 'url': 'https://github.com/ssoe94/wj_reporting/blob/4e58afff/backend/injection/models.py', 'label': '기존 참고 · 금형·C/T·계측 모델'},
        ],
        'completion_note': '',
        'verification_note': '비용 연결은 계획 단계다. 이번 검토에서 실제 금액 자료를 조회하지 않았으며 절감액을 추정하지 않았다. 가동 설비 비율이나 계획 달성률은 OEE가 아니다.',
        'release_state': 'unreleased',
        'sort_order': 100,
    },
]
