# Generated by Django 5.2.3 on 2026-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes_oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MESCredential',
            fields=[
                ('actor_id', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('mes_user_id', models.CharField(editable=False, max_length=19)),
                ('app_id', models.CharField(editable=False, max_length=19)),
                ('tenant_reference', models.CharField(editable=False, max_length=128)),
                ('login_digest', models.CharField(editable=False, max_length=64)),
                ('authorization_digest', models.CharField(editable=False, max_length=64)),
                ('policy_reference', models.CharField(editable=False, max_length=128)),
                ('key_id', models.CharField(editable=False, max_length=32)),
                ('ciphertext', models.BinaryField(default=bytes)),
                ('verified_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('provider_expires_at', models.DateTimeField()),
                ('idle_expires_at', models.DateTimeField(db_index=True)),
                ('consent_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('version', models.PositiveBigIntegerField(default=1, editable=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MESCredentialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('action', models.CharField(editable=False, max_length=24)),
                ('reason', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MESLoginSession',
            fields=[
                ('digest', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('authorization_digest', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MESLoginTicket',
            fields=[
                ('digest', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.PositiveBigIntegerField(editable=False)),
                ('login_digest', models.CharField(editable=False, max_length=64)),
                ('authorization_digest', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('login_revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
