from django.urls import path
from .views import (
    ProductionConsoleView,
    ProductionDashboardView,
    ProductionAiBriefingView,
    ProductionAiAskView,
    ProductionExecutionUpsertView,
    InjectionActivityConfirmationView,
    InjectionDowntimeConfirmationView,
    ProductionMesReportStatsView,
    ProductionPlanChangeLogView,
    ProductionPlanDatesView,
    ProductionPlanSummaryView,
    ProductionStatusView,
    ProductionPartCavityView,
    DebugPlanView,
    MachiningManualReportConfirmMatchView,
    MachiningManualReportView,
    MachiningProvisionView,
    MachiningReconciliationView,
    ProductionPlanListView,
    ProductionPlanDetailView,
    ProductionPlanPartSearchView,
)

urlpatterns = [
    path('console/', ProductionConsoleView.as_view(), name='production-console'),
    path('ai/briefing/', ProductionAiBriefingView.as_view(), name='production-ai-briefing'),
    path('ai/ask/', ProductionAiAskView.as_view(), name='production-ai-ask'),
    path('dashboard/', ProductionDashboardView.as_view(), name='production-dashboard'),
    path('executions/upsert/', ProductionExecutionUpsertView.as_view(), name='production-execution-upsert'),
    path(
        'injection-downtime-confirmations/',
        InjectionDowntimeConfirmationView.as_view(),
        name='injection-downtime-confirmations',
    ),
    path(
        'injection-activity-confirmations/',
        InjectionActivityConfirmationView.as_view(),
        name='injection-activity-confirmations',
    ),
    path('mes-report-stats/', ProductionMesReportStatsView.as_view(), name='production-mes-report-stats'),
    path('machining/provision/', MachiningProvisionView.as_view(), name='machining-provision'),
    path('machining/manual-reports/', MachiningManualReportView.as_view(), name='machining-manual-reports'),
    path('machining/reconciliation/', MachiningReconciliationView.as_view(), name='machining-reconciliation'),
    path(
        'machining/reconciliation/<int:manual_report_id>/confirm/',
        MachiningManualReportConfirmMatchView.as_view(),
        name='machining-reconciliation-confirm',
    ),
    path('plan-dates/', ProductionPlanDatesView.as_view(), name='production-plan-dates'),
    path('plan-change-logs/', ProductionPlanChangeLogView.as_view(), name='production-plan-change-logs'),
    path('plan-summary/', ProductionPlanSummaryView.as_view(), name='production-plan-summary'),
    path('plans/', ProductionPlanListView.as_view(), name='production-plan-list'),
    path('plans/<int:pk>/', ProductionPlanDetailView.as_view(), name='production-plan-detail'),
    path('plan-parts/', ProductionPlanPartSearchView.as_view(), name='production-plan-part-search'),
    path('part-cavity/', ProductionPartCavityView.as_view(), name='production-part-cavity'),
    path('status/', ProductionStatusView.as_view(), name='production-status'),
    path('debug-plan/', DebugPlanView.as_view(), name='debug-plan'),
]
