# Generated by Django 5.2.3 on 2025-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(db_index=True)),
                ('plan_type', models.CharField(db_index=True, max_length=20)),
                ('machine_name', models.CharField(db_index=True, max_length=100)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('part_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('part_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('planned_quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan_date', 'machine_name'],
                'indexes': [models.Index(fields=['plan_date', 'plan_type'], name='production__plan_da_6777aa_idx')],
                'unique_together': {('plan_date', 'machine_name', 'part_no', 'lot_no', 'plan_type')},
            },
        ),
    ]
