# Generated by Django 5.2.3 on 2025-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ['plan_date', 'machine_name', 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='productionplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productionplan',
            unique_together={('plan_date', 'machine_name', 'part_no', 'lot_no', 'plan_type', 'sequence')},
        ),
    ]
