# Generated by Django 5.2.3 on 2025-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_add_sequence_to_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='sequence',
            field=models.IntegerField(default=-1),
        ),
    ]
