# Generated by Django 5.2.3 on 2026-01-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionplanpart'),
        ('production', '0004_productionpartcavity'),
    ]

    operations = [
    ]
