# Generated by Django 5.2.3 on 2026-05-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_productionplanchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachiningManualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('plan_date', models.DateField(db_index=True)),
                ('plan_type', models.CharField(db_index=True, default='machining', max_length=20)),
                ('plan_identity_hash', models.CharField(db_index=True, max_length=64)),
                ('machine_name', models.CharField(db_index=True, max_length=100)),
                ('equipment_key', models.CharField(db_index=True, max_length=50)),
                ('part_no', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(default=-1)),
                ('planned_qty_at_report', models.IntegerField(default=0)),
                ('good_qty', models.IntegerField(default=0)),
                ('defect_qty', models.IntegerField(default=0)),
                ('total_reported_qty', models.IntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('matched', 'Matched'), ('mismatch', 'Mismatch'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('credit_business_date', models.DateField(db_index=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-business_date', 'machine_name', 'sequence', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MachiningManualReportDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_category', models.CharField(blank=True, default='processing', max_length=40)),
                ('defect_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manual_report_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachiningManualReportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_qty', models.IntegerField(default=0)),
                ('match_confidence', models.CharField(choices=[('exact', 'Exact'), ('probable', 'Probable'), ('manual_confirmed', 'Manual confirmed')], default='probable', max_length=40)),
                ('match_reason', models.CharField(blank=True, default='', max_length=255)),
                ('matched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['manual_report_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='machiningmanualreport',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machining_manual_reports', to='production.productionplan'),
        ),
        migrations.AddField(
            model_name='machiningmanualreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machining_manual_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machiningmanualreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machining_manual_report_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machiningmanualreportdefect',
            name='manual_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_items', to='production.machiningmanualreport'),
        ),
        migrations.AddField(
            model_name='machiningmanualreportmatch',
            name='manual_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='production.machiningmanualreport'),
        ),
        migrations.AddField(
            model_name='machiningmanualreportmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machining_manual_report_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machiningmanualreportmatch',
            name='mes_report_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_matches', to='production.productionmesreportrecord'),
        ),
        migrations.AddIndex(
            model_name='machiningmanualreport',
            index=models.Index(fields=['business_date', 'status'], name='production__busines_aa30ba_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmanualreport',
            index=models.Index(fields=['plan_date', 'equipment_key', 'part_no'], name='production__plan_da_57cfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmanualreport',
            index=models.Index(fields=['credit_business_date', 'status'], name='production__credit__d589df_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmanualreportdefect',
            index=models.Index(fields=['defect_category', 'defect_type'], name='production__defect__ab69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='machiningmanualreportmatch',
            index=models.Index(fields=['matched_at'], name='production__matched_81c748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='machiningmanualreportmatch',
            unique_together={('manual_report', 'mes_report_record')},
        ),
    ]
