# Generated by Django 5.2.3 on 2026-07-11 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_reset_cavity_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionDowntimeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('machine_key', models.CharField(db_index=True, max_length=40)),
                ('machine_label', models.CharField(max_length=100)),
                ('detected_type', models.CharField(choices=[('mold_change', 'Mold change'), ('core_change', 'Core change'), ('tuning', 'Tuning'), ('production_stop', 'Production stop')], max_length=30)),
                ('detected_start', models.DateTimeField(db_index=True)),
                ('detected_end', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(choices=[('confirmed', 'Confirmed downtime'), ('dismissed', 'Not downtime')], db_index=True, default='confirmed', max_length=20)),
                ('reason_code', models.CharField(choices=[('mold_change', 'Mold change'), ('core_change', 'Core change'), ('tuning', 'Tuning'), ('mechanical_failure', 'Machine failure'), ('mold_issue', 'Mold issue'), ('material_wait', 'Material wait'), ('quality_check', 'Quality check'), ('planned_stop', 'Planned stop'), ('staffing', 'Staffing or shift change'), ('other', 'Other'), ('not_stop', 'Not downtime')], max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detected_start', '-id'],
            },
        ),
        migrations.AddField(
            model_name='injectiondowntimeconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection_downtime_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='injectiondowntimeconfirmation',
            index=models.Index(fields=['business_date', 'resolution'], name='production__busines_accb96_idx'),
        ),
        migrations.AddIndex(
            model_name='injectiondowntimeconfirmation',
            index=models.Index(fields=['business_date', 'machine_key', 'detected_start'], name='production__busines_d7ca85_idx'),
        ),
    ]
