# Generated by Django 5.2.3 on 2026-07-11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_injectiondowntimeconfirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionActivityConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('machine_key', models.CharField(db_index=True, max_length=40)),
                ('machine_label', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('production', 'Production'), ('test_shot', 'Test shot'), ('mold_check', 'Mold check'), ('machine_check', 'Machine check'), ('maintenance', 'Maintenance'), ('quality_check', 'Quality check'), ('other', 'Other')], max_length=30)),
                ('part_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('shot_count', models.PositiveIntegerField(default=0)),
                ('last_shot_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection_activity_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_date', 'machine_key'],
                'unique_together': {('business_date', 'machine_key')},
            },
        ),
        migrations.AddIndex(
            model_name='injectionactivityconfirmation',
            index=models.Index(fields=['business_date', 'activity_type'], name='prod_act_bus_type_idx'),
        ),
    ]
