# Generated by Django 5.2.3 on 2026-10-08 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_workflow(apps, schema_editor):
    from collections import Counter
    from decimal import Decimal
    import hashlib
    import json
    Plan = apps.get_model('production', 'ProductionPlan')
    Identity = apps.get_model('production', 'PlanWorkIdentity')
    Revision = apps.get_model('production', 'PlanWorkRevision')
    Lock = apps.get_model('production', 'PlanWorkflowLock')
    alias = schema_editor.connection.alias
    for plan_type in ('injection', 'machining'):
        Lock.objects.using(alias).get_or_create(plan_type=plan_type)
    fields = ('plan_date', 'plan_type', 'machine_name', 'part_no', 'lot_no', 'model_name',
              'part_spec', 'product_family_code', 'product_family_name', 'is_finished_product',
              'sequence', 'planned_quantity')
    def key(row):
        return (str(row.plan_date), row.plan_type, row.machine_name, row.part_no, row.lot_no or '')
    counts = Counter(key(row) for row in Plan.objects.using(alias).all().iterator())
    for row in Plan.objects.using(alias).filter(work_uid__isnull=True).iterator():
        work = Identity.objects.using(alias).create(plan_type=row.plan_type,
            resolution='identified' if row.part_no and counts[key(row)] == 1 else 'confirmation')
        snapshot = {field: getattr(row, field) for field in fields}
        snapshot['plan_date'] = str(row.plan_date)
        snapshot['planned_quantity'] = format(Decimal(str(row.planned_quantity)), 'f')
        fingerprint = hashlib.sha256(json.dumps(snapshot, sort_keys=True, ensure_ascii=False,
                                                separators=(',', ':')).encode()).hexdigest()
        Revision.objects.using(alias).create(work=work, version=1, snapshot=snapshot,
                                            fingerprint=fingerprint, change='baseline')
        Plan.objects.using(alias).filter(pk=row.pk).update(work_uid=work.uid, work_version=1)



class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_mestaskactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWorkflowLock',
            fields=[
                ('plan_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanWorkIdentity',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(db_index=True, max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('resolution', models.CharField(default='identified', max_length=24)),
                ('candidates', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlanWorkOrder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(max_length=20)),
                ('members', models.JSONField(default=list)),
                ('setup_fingerprint', models.CharField(max_length=64)),
                ('approved_snapshot', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('mes_id', models.CharField(blank=True, max_length=19)),
                ('actual_started_at', models.DateTimeField(null=True)),
                ('reported_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('inbound_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('observed_at', models.DateTimeField(null=True)),
                ('observation_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='productionplan',
            name='work_uid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='work_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='PlanMesRequest',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('operation', models.CharField(max_length=20)),
                ('state', models.CharField(default='disabled', max_length=24)),
                ('intent', models.JSONField()),
                ('contract', models.JSONField(default=dict)),
                ('blockers', models.JSONField(default=list)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='production.planworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMesRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=24)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='production.planmesrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PlanWorkRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('change', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='production.planworkidentity')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMaterialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='production.planworkrevision')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMaterialDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20)),
                ('part_no', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan_type', 'part_no', 'version'), name='plan_material_default_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='planworkrevision',
            constraint=models.UniqueConstraint(fields=('work', 'version'), name='plan_work_revision_uniq'),
        ),
        migrations.RunPython(seed_workflow, reverse_code=migrations.RunPython.noop),
    ]
