# Generated by Django 5.2.3 on 2026-10-09 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_plan_material_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesCreateDiagnostic',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('state', models.CharField(default='prepared', max_length=24)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('mes_id', models.CharField(blank=True, max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesCreateDiagnosticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=24)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='production.mescreatediagnostic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mescreatediagnostic',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='mes_create_diagnostic_code_uniq'),
        ),
    ]
