export const inspectionKanbanCopy = {
  ko: {
    title: '설비별 검사요청',
    filterTitle: '검사요청 필터', search: '설비·품번·계획·작업 검색', allMachines: '전체 설비', unmappedMachine: '설비 미매핑',
    allStages: '전체', filterWaiting: '미처리', filterProgress: '검사 중', filterCompleted: '완료 확인', filterBlocked: '확인·조치 필요',
    delayed: '지연', delayUnavailable: '지연 기준 미연결', delayHint: '검사 기한이 연결되지 않아 지연 여부를 판정할 수 없습니다.',
    filterScope: '상태 필터는 조회된 WJ 검사요청에 적용됩니다. MES 과거 관측은 전체 상태에서 확인하세요.',
    filterResult: '조건에 맞는 WJ 요청', clearFilters: '필터 초기화', noMatches: '조건에 맞는 요청이나 계획이 없습니다.', previousDayOpen: '이전 생산일 미완료 요청', date: '생산일', current: '현재 생산일', refresh: '칸반 새로고침',
    day: '상하이 08:00 ~ 다음 날 08:00', waiting: '검사 대기', in_progress: '진행 중', completed: 'MES 완료 확인', blocked: '확인·조치 필요',
    general: '연동시험', first: '초도', process: '공정', final: '최종', reinspection: '재검', machine: '호기', empty: '표시할 검사요청 없음',
    plan: 'WJ 생산계획', planMissing: '계획 없음', planUnknown: '계획 매핑·범위 미확인', running: 'WJ 진행 기록', scheduled: '계획', paused: 'WJ 중단 기록',
    plansMore: '나머지 계획', noPart: '품번 미기록', lot: '로트', seq: '순서', elapsed: '요청 후', minute: '분', hour: '시간', dayUnit: '일',
    unmapped: '설비 미매핑 요청', unmappedHint: '설비를 확인한 후 요청을 선택하세요.', unmappedPlans: '설비 미매핑 계획',
    mapping: '설비명 기준 표시입니다. MES 자원·작업 연결과 계획 최신성은 미확인입니다.',
    listed: '계획 품번·로트 표시 일치', discrepancy: '계획 품번·로트 불일치', alignmentUnknown: '계획 대조 미확인',
    truncation: '조회 상한에 도달했습니다. 요청·계획·진행 기록이 일부만 표시될 수 있습니다.',
    partial: '계획 매핑 또는 조회 범위가 미확인입니다. 계획 없음으로 중단을 판단하지 마세요.',
    refreshed: '조회', planUpdated: '계획 변경 기록', retained: '이전 미완료·완료 미확인 요청도 함께 표시합니다.',
    dryRun: '자동화 검토 요약', dryRunHint: '중단·재개 자동 실행은 꺼져 있습니다.', reviewPause: '미계획 작업 검토', reviewResume: '재개 조건 검토', reviewAlignment: '계획 연결 검토',
    dryRunBasis: '작업 연결·MES 상태·설비 매핑·수동 재정의·재개 시 초도검사 정책 확인 필요',
    stale: '새 조회에 실패했습니다. 아래는 마지막 조회 결과입니다.', localReview: 'WJ 상태', owner: '담당',
    executionHint: 'WJ·MES 실행 기록만으로 실제 설비 가동이나 현재 작업을 판단할 수 없습니다. 같은 설비의 여러 계획을 함께 확인하세요.',
    displayedRequests: '이 조회의 표시 요청', displayCount: '표시', scopeHint: '표시 요청만 집계합니다. 전체 MES QC 건수와 미처리 건수는 미확인이며, 이 집계는 미처리 요청만을 뜻하지 않습니다.',
  },
  zh: {
    title: '按设备查看检验申请',
    filterTitle: '检验申请筛选', search: '搜索设备、料号、计划、作业', allMachines: '全部设备', unmappedMachine: '设备未映射',
    allStages: '全部', filterWaiting: '未处理', filterProgress: '检验中', filterCompleted: '完成已确认', filterBlocked: '需确认·处理',
    delayed: '延迟', delayUnavailable: '未关联延迟判定依据', delayHint: '尚未关联检验期限，无法判断是否延迟。',
    filterScope: '状态筛选仅用于已查询的 WJ 检验申请。MES 历史观测可在全部状态中查看。',
    filterResult: '符合条件的 WJ 申请', clearFilters: '重置筛选', noMatches: '没有符合条件的申请或计划。', previousDayOpen: '此前生产日未完成申请', date: '生产日', current: '当前生产日', refresh: '刷新看板',
    day: '上海 08:00 至次日 08:00', waiting: '待检验', in_progress: '进行中', completed: 'MES 完成已确认', blocked: '需确认·处理',
    general: '接口测试', first: '首检', process: '过程检验', final: '最终检验', reinspection: '复检', machine: '号机', empty: '暂无显示的检验申请',
    plan: 'WJ 生产计划', planMissing: '无计划', planUnknown: '计划映射·范围未确认', running: 'WJ 进行记录', scheduled: '计划', paused: 'WJ 暂停记录',
    plansMore: '其余计划', noPart: '料号未记录', lot: '批次', seq: '顺序', elapsed: '申请后', minute: '分钟', hour: '小时', dayUnit: '天',
    unmapped: '设备未映射申请', unmappedHint: '请核对设备后选择申请。', unmappedPlans: '设备未映射计划',
    mapping: '按设备名称展示。MES 资源·作业关联及计划时效未确认。',
    listed: '计划料号·批次显示一致', discrepancy: '计划料号·批次不一致', alignmentUnknown: '计划核对未确认',
    truncation: '已达到查询上限，申请、计划或进行记录可能仅显示一部分。',
    partial: '计划映射或查询范围未确认，不得仅因无计划而判断停工。',
    refreshed: '查询', planUpdated: '计划变更记录', retained: '同时显示此前未完成、完成未确认的申请。',
    dryRun: '自动化检查汇总', dryRunHint: '自动暂停·恢复未启用。', reviewPause: '核对无计划作业', reviewResume: '核对恢复条件', reviewAlignment: '核对计划关联',
    dryRunBasis: '需确认作业关联、MES 状态、设备映射、人工覆盖及恢复时首检政策',
    stale: '新查询失败，以下为上次查询结果。', localReview: 'WJ 状态', owner: '负责人',
    executionHint: 'WJ、MES 的执行记录不能证明设备实际运行或当前作业。请同时核对同一设备的多份计划。',
    displayedRequests: '此次查询显示的申请', displayCount: '显示', scopeHint: '仅统计显示的申请。MES 全部 QC 数量与待处理数量尚未确认，此统计并非仅包含待处理申请。',
  },
};
