import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { assertAuthSessionCurrent } from '@/domains/auth/auth-transition';
import { getInspectionRequest, getInspectionRoleSettings, mutateInspectionRequest, mutateInspectionRole } from './api';
import type { InspectionCapabilities, InspectionEvidence, InspectionMeasurement, InspectionRequest } from './model';
import { inspectionCopy, inspectionHistoryActionLabel, inspectionHistoryResultLabel, inspectionRequestStatusLabels, inspectionTime } from './copy';
import { inspectionRoleCopy } from './roleCopy';
import { inspectionAreas, inspectionRoleFinalJudgement, inspectionRoleItemEditable, inspectionRoleMappingValid, inspectionRoleMeasurements, inspectionRoleReconcileDraft, inspectionRoleSavePayload } from './roleModel';
import type { InspectionArea, InspectionRoleAction, InspectionRoleSettings } from './roleModel';
import { createInspectionKey, inspectionError, safeInspectionEvidenceUrl } from './workflow';
import type { InspectionAction } from './workflow';
import { roleShiftDateCovered } from './roleShiftSettingsModel';

type Attempt = { kind: 'role' | 'legacy'; action: InspectionRoleAction | InspectionAction; payload: Record<string, unknown>; key: string };
type SummaryDraft = { inspected_quantity: string; accepted_quantity: string; rejected_quantity: string; notes: string };
type DraftRecovery = { schema: 1; user_id: number; request_id: number; saved_at: number; request_version: number; config_version: number; area_versions: Record<string, number>; measurements: InspectionMeasurement[]; evidence: Record<InspectionArea, InspectionEvidence[]>; summary: SummaryDraft; reason: string; judgements: Record<InspectionArea, '' | 'pass' | 'fail'>; shift_id: string; shift_date: string; item_areas: Record<string, string>; attempt: Attempt | null };
const summaryDraft = (request: InspectionRequest): SummaryDraft => ({ inspected_quantity: request.inspected_quantity || '', accepted_quantity: request.accepted_quantity || '', rejected_quantity: request.rejected_quantity || '', notes: request.notes || '' });
const areaEvidence = (request: InspectionRequest): Record<InspectionArea, InspectionEvidence[]> => ({ appearance: request.role_workflow?.areas.find((row) => row.area === 'appearance')?.evidence || [], dimension: request.role_workflow?.areas.find((row) => row.area === 'dimension')?.evidence || [] });
const recoveryKey = (userId: number, requestId: number) => `wj-inspection-role-draft:v1:${userId}:${requestId}`;
function readRecovery(userId: number, requestId: number): DraftRecovery | null {
  try {
    const raw = sessionStorage.getItem(recoveryKey(userId, requestId));
    if (!raw) return null;
    const value = JSON.parse(raw) as DraftRecovery;
    if (value.schema !== 1 || value.user_id !== userId || value.request_id !== requestId || !Array.isArray(value.measurements) || !value.evidence || !Array.isArray(value.evidence.appearance) || !Array.isArray(value.evidence.dimension) || !value.summary || !Number.isSafeInteger(value.request_version) || !Number.isSafeInteger(value.config_version) || !value.area_versions || !Number.isFinite(value.saved_at) || value.saved_at > Date.now() || (!value.attempt && Date.now() - value.saved_at > 86_400_000)) return null;
    if (value.attempt && (!['role-configure', 'area-save', 'area-complete', 'area-reopen', 'role-results', 'submit', 'approve', 'reject', 'reinspect', 'review-failure'].includes(value.attempt.action) || !['role', 'legacy'].includes(value.attempt.kind) || !/^[0-9a-f-]{36}$/i.test(value.attempt.key) || !value.attempt.payload || typeof value.attempt.payload !== 'object')) return null;
    return value;
  } catch { return null; }
}

export default function RoleInspectionRequestDetail({ initial, userId, sessionId, lang, globalCapabilities, onChanged, onDirty, onLocked, onOpenSettings }: {
  initial: InspectionRequest; userId: number; sessionId: string | null; lang: 'ko' | 'zh'; globalCapabilities: InspectionCapabilities;
  onChanged: (request: InspectionRequest) => void; onDirty: (dirty: boolean) => void; onLocked: (locked: boolean, pending: boolean) => void; onOpenSettings?: () => void;
}) {
  const text = inspectionRoleCopy[lang]; const common = inspectionCopy[lang];
  const [request, setRequest] = useState(initial);
  const workflow = request.role_workflow!;
  const [measurements, setMeasurements] = useState(() => inspectionRoleMeasurements(initial));
  const [evidence, setEvidence] = useState(() => areaEvidence(initial));
  const [summary, setSummary] = useState(() => summaryDraft(initial));
  const [reason, setReason] = useState('');
  const [judgements, setJudgements] = useState<Record<InspectionArea, '' | 'pass' | 'fail'>>({ appearance: '', dimension: '' });
  const [settings, setSettings] = useState<InspectionRoleSettings | null>(null);
  const [shiftId, setShiftId] = useState('');
  const [shiftDate, setShiftDate] = useState('');
  const [itemAreas, setItemAreas] = useState<Record<string, string>>(() => ({ ...initial.role_workflow?.item_areas }));
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [attempt, setAttempt] = useState<Attempt | null>(null); const [conflict, setConflict] = useState(false); const [needsReload, setNeedsReload] = useState(false); const [latest, setLatest] = useState<InspectionRequest | null>(null);
  const [recovery, setRecovery] = useState(() => readRecovery(userId, initial.id));
  const mounted = useRef(true); const lock = useRef(false);
  const baseVersions = useRef({ request_version: initial.version, config_version: initial.role_workflow!.config_version, area_versions: Object.fromEntries(initial.role_workflow!.areas.map((area) => [area.area, area.version])) });
  const ownsSession = useCallback(() => { if (!mounted.current) return false; try { assertAuthSessionCurrent(sessionId); return true; } catch { return false; } }, [sessionId]);
  const originalRows = useMemo(() => inspectionRoleMeasurements(request), [request]);
  const areaDirty = (area: InspectionArea) => JSON.stringify(measurements.filter((row) => workflow.item_areas[row.item_id] === area)) !== JSON.stringify(originalRows.filter((row) => workflow.item_areas[row.item_id] === area)) || JSON.stringify(evidence[area]) !== JSON.stringify(areaEvidence(request)[area]);
  const summaryDirty = JSON.stringify(summary) !== JSON.stringify(summaryDraft(request));
  const dataDirty = inspectionAreas.some(areaDirty) || summaryDirty;
  const verdictDirty = inspectionAreas.some((area) => workflow.areas.find((row) => row.area === area)?.can_complete && Boolean(judgements[area]));
  const dirty = dataDirty || verdictDirty || Boolean(reason.trim()) || Boolean(shiftId) || Boolean(shiftDate) || JSON.stringify(itemAreas) !== JSON.stringify(workflow.item_areas);
  const blocked = busy || Boolean(attempt) || conflict || needsReload || Boolean(recovery);
  const finalJudgement = inspectionRoleFinalJudgement(workflow);
  const canSummaryEdit = globalCapabilities.can_manage === true && request.assigned_to === userId && request.status === 'draft' && !['pending', 'unknown', 'succeeded'].includes(request.sync_status) && request.mes_completion_status !== 'completed' && !blocked;
  const canConfigure = !workflow.configured && workflow.can_configure === true && globalCapabilities.can_manage_role_settings === true;
  const activeSettings = settings?.settings.filter((setting) => setting.active) || [];
  const persist = (pending: Attempt | null = attempt) => {
    if (!ownsSession()) return;
    try { sessionStorage.setItem(recoveryKey(userId, request.id), JSON.stringify({ schema: 1, user_id: userId, request_id: request.id, saved_at: Date.now(), ...baseVersions.current, measurements, evidence, summary, reason, judgements, shift_id: shiftId, shift_date: shiftDate, item_areas: itemAreas, attempt: pending })); } catch { /* Optional, per-account and per-tab recovery. */ }
  };
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { if (ownsSession()) onDirty(dirty || Boolean(recovery)); }, [dirty, recovery, onDirty, ownsSession]);
  useEffect(() => { if (ownsSession()) onLocked(busy || Boolean(attempt) || Boolean(recovery?.attempt) || needsReload, busy); }, [busy, attempt, recovery, needsReload, onLocked, ownsSession]);
  useEffect(() => {
    if (!ownsSession() || !canConfigure) return;
    let active = true;
    void getInspectionRoleSettings(sessionId).then((result) => { if (active && ownsSession()) setSettings(result); }).catch((cause) => { if (active && ownsSession()) setError(inspectionError(cause, common.loadError).message); });
    return () => { active = false; };
  }, [canConfigure, common.loadError, ownsSession, sessionId]);
  useEffect(() => {
    if (!ownsSession() || recovery) return;
    if (dirty || attempt) persist(attempt);
    else { try { sessionStorage.removeItem(recoveryKey(userId, request.id)); } catch { /* Optional recovery. */ } }
  });
  const adopt = (updated: InspectionRequest, action?: Attempt['action'], preserveDraft = false) => {
    if (!ownsSession() || updated.id !== request.id || !updated.role_workflow) return;
    baseVersions.current = { request_version: updated.version, config_version: updated.role_workflow.config_version, area_versions: Object.fromEntries(updated.role_workflow.areas.map((area) => [area.area, area.version])) };
    setRequest(updated); onChanged(updated);
    setMeasurements(preserveDraft || action === 'role-results' ? inspectionRoleReconcileDraft(measurements, updated, userId) : inspectionRoleMeasurements(updated));
    if (preserveDraft || action === 'role-results') { const freshEvidence = areaEvidence(updated); setEvidence(Object.fromEntries(inspectionAreas.map((area) => [area, updated.role_workflow!.areas.find((row) => row.area === area)?.assigned_to === userId && updated.role_workflow!.areas.find((row) => row.area === area)?.can_save ? evidence[area] : freshEvidence[area]])) as Record<InspectionArea, InspectionEvidence[]>); } else setEvidence(areaEvidence(updated));
    if (!preserveDraft && (action === 'role-results' || !summaryDirty)) setSummary(summaryDraft(updated));
    if (!preserveDraft || updated.role_workflow.configured) { setItemAreas({ ...updated.role_workflow.item_areas }); setShiftId(''); setShiftDate(''); }
    setJudgements({ appearance: '', dimension: '' }); setAttempt(null); setConflict(false); setNeedsReload(false); setLatest(null); setRecovery(null); if (!preserveDraft) setReason('');
  };
  const run = async (pending: Attempt) => {
    if (!ownsSession() || lock.current) return;
    lock.current = true; onLocked(true, true); setBusy(true); setAttempt(pending); setError(''); setMessage(''); persist(pending);
    try {
      const updated = pending.kind === 'role'
        ? await mutateInspectionRole(request.id, { action: pending.action as InspectionRoleAction, payload: pending.payload, key: pending.key }, sessionId)
        : await mutateInspectionRequest(request.id, { action: pending.action as InspectionAction, payload: pending.payload, key: pending.key }, sessionId);
      if (!ownsSession()) return;
      if (pending.action === 'reinspect' && updated.id !== request.id) {
        setAttempt(null); setRecovery(null); try { sessionStorage.removeItem(recoveryKey(userId, request.id)); } catch { /* Optional recovery. */ }
        onChanged(updated); return;
      }
      let current = updated; let reloadFailed = false;
      try { current = await getInspectionRequest(updated.id, sessionId); } catch { reloadFailed = true; }
      if (!ownsSession()) return;
      adopt(current, pending.action);
      if (reloadFailed) { setNeedsReload(true); setError(common.stateRefreshFailure); } else setMessage(text.saved);
    } catch (cause) {
      if (!ownsSession()) return;
      const failure = inspectionError(cause, common.failure, request.id);
      setConflict(failure.conflict); setError(failure.conflict ? text.conflict : failure.uncertain ? text.uncertain : failure.message);
      if (!failure.uncertain) { setAttempt(null); persist(null); }
    } finally { lock.current = false; if (ownsSession()) setBusy(false); }
  };
  const send = (action: Attempt['action'], payload: Record<string, unknown>, kind: Attempt['kind'] = 'role') => { if (ownsSession() && !blocked) void run({ kind, action, payload, key: createInspectionKey() }); };
  const updateMeasurement = (itemId: string, patch: Partial<InspectionMeasurement>) => { if (!ownsSession() || blocked || !inspectionRoleItemEditable(workflow, itemId, userId)) return; setMeasurements((rows) => rows.map((row) => row.item_id === itemId ? { ...row, ...patch } : row)); setMessage(''); };
  const saveArea = (area: InspectionArea) => {
    try {
      const payload = inspectionRoleSavePayload(workflow, area, userId, measurements, evidence[area]);
      if ((payload.measurements as InspectionMeasurement[]).some((row) => row.evidence_url && !safeInspectionEvidenceUrl(row.evidence_url)) || evidence[area].some((row) => row.url && !safeInspectionEvidenceUrl(row.url))) { setError(common.unsafeEvidence); return; }
      send('area-save', payload);
    } catch { setError(text.noPermission); }
  };
  const compare = async () => {
    if (!ownsSession() || busy || attempt) return;
    setBusy(true);
    try { const result = await getInspectionRequest(request.id, sessionId); if (ownsSession()) setLatest(result); }
    catch (cause) { if (ownsSession()) setError(inspectionError(cause, common.loadError).message); }
    finally { if (ownsSession()) setBusy(false); }
  };
  const configure = () => {
    const shift = activeSettings.find((setting) => String(setting.id) === shiftId);
    if (!shift || !/^\d{4}-\d{2}-\d{2}$/.test(shiftDate) || !inspectionRoleMappingValid(request.inspection_items.map((item) => item.id), itemAreas) || !reason.trim()) { setError(text.mappingInvalid); return; }
    if (!roleShiftDateCovered(shift, shiftDate)) { setError(text.outsidePeriod); return; }
    send('role-configure', { config_version: workflow.config_version, shift_setting_id: shift.id, shift_version: shift.version, shift_date: shiftDate, item_areas: itemAreas, reason: reason.trim() });
  };
  const historyRows = [
    ...request.audit.map((row) => ({ key: `audit-${row.id}`, at: row.created_at, actor: row.actor_name || '—', action: inspectionHistoryActionLabel(lang, row.action), result: inspectionHistoryResultLabel(lang, row.action, row.status) })),
    ...request.operations.map((row) => ({ key: `operation-${row.id}`, at: row.created_at, actor: '—', action: inspectionHistoryActionLabel(lang, row.scope.split(':').slice(-1)[0]), result: inspectionHistoryResultLabel(lang, '', row.status, true) })),
  ].sort((a, b) => (Date.parse(b.at) || 0) - (Date.parse(a.at) || 0));
  return <section className="inspection-detail inspection-role-detail" aria-labelledby="inspection-detail-title" aria-busy={busy}>
    <div className="inspection-detail-heading"><div><h2 id="inspection-detail-title">{request.part_no || request.work_order_ref || common.requests}</h2><p>{text.title}{workflow.shift_snapshot?.label ? ` · ${workflow.shift_snapshot.label}` : ''}</p></div><span className="inspection-status" data-status={request.status}>{inspectionRequestStatusLabels[lang][request.status]}</span></div>
    {error && <p className="inspection-message is-error" role="alert">{error}</p>}{message && <p className="inspection-message is-success" role="status">{message}</p>}
    {attempt && !busy && <div className="inspection-message"><p>{text.uncertain}</p><button type="button" className="inspection-button" onClick={() => void run(attempt)}>{text.retry}</button></div>}
    {recovery && <div className="inspection-message"><strong>{common.recovery}</strong><p>{common.recoveryHint}</p><div className="inspection-actions"><button type="button" className="inspection-button" onClick={() => { if (!ownsSession()) return; baseVersions.current = { request_version: recovery.request_version, config_version: recovery.config_version, area_versions: recovery.area_versions }; setMeasurements(recovery.measurements); setEvidence(recovery.evidence); setSummary(recovery.summary); setReason(recovery.reason); setJudgements(recovery.judgements || { appearance: '', dimension: '' }); setShiftId(recovery.shift_id || ''); setShiftDate(recovery.shift_date || ''); setItemAreas(recovery.item_areas || {}); setAttempt(recovery.attempt); setConflict(recovery.request_version !== request.version || recovery.config_version !== workflow.config_version || workflow.areas.some((area) => recovery.area_versions[area.area] !== area.version)); setRecovery(null); }}>{common.restore}</button>{!recovery.attempt && <button type="button" className="inspection-button" onClick={() => { if (ownsSession()) { setRecovery(null); try { sessionStorage.removeItem(recoveryKey(userId, request.id)); } catch { /* Optional recovery. */ } } }}>{common.discardRecovery}</button>}</div></div>}
    {conflict && <div className="inspection-message"><p>{text.conflict}</p><button type="button" className="inspection-button" disabled={busy} onClick={() => void compare()}>{text.compare}</button>{latest?.role_workflow && <><p>{common.version} {request.version} → {latest.version}</p><div className="inspection-table-scroll"><table className="inspection-history-table"><thead><tr><th>{common.itemName}</th><th>{lang === 'ko' ? '내 입력' : '我的输入'}</th><th>{lang === 'ko' ? '현재 저장 값' : '当前保存值'}</th></tr></thead><tbody>{measurements.filter((row) => workflow.item_areas[row.item_id] && workflow.areas.find((area) => area.area === workflow.item_areas[row.item_id])?.assigned_to === userId).map((row) => <tr key={row.item_id}><td>{request.inspection_items.find((item) => item.id === row.item_id)?.label}</td><td>{row.value || '—'} · {row.judgement || '—'}</td><td>{inspectionRoleMeasurements(latest).find((item) => item.item_id === row.item_id)?.value || '—'} · {inspectionRoleMeasurements(latest).find((item) => item.item_id === row.item_id)?.judgement || '—'}</td></tr>)}</tbody></table></div><div className="inspection-actions"><button type="button" className="inspection-button" onClick={() => { if (ownsSession()) { adopt(latest, undefined, true); setError(''); } }}>{text.useDraft}</button><button type="button" className="inspection-button" onClick={() => { if (ownsSession()) { setSummary(summaryDraft(latest)); adopt(latest); setError(''); } }}>{text.discard}</button></div></>}</div>}
    {!workflow.configured && <section className="inspection-section"><h3>{text.configuration}</h3><p className="inspection-muted">{text.empty}</p><p className="inspection-muted">{text.configurationHint}</p>{onOpenSettings && <button type="button" className="inspection-button" disabled={blocked} onClick={onOpenSettings}>{text.settings}</button>}{!canConfigure && <p>{text.denied}</p>}{canConfigure && <fieldset disabled={blocked}><label>{lang === 'ko' ? '검사 교대 날짜' : '检验班次日期'} *<input id="inspection-role-shift-date" type="date" value={shiftDate} onChange={(event) => { if (ownsSession()) setShiftDate(event.target.value); }} /></label><label>{text.label}<select id="inspection-role-shift-setting" value={shiftId} onChange={(event) => { if (ownsSession()) setShiftId(event.target.value); }}><option value="">{text.choose}</option>{activeSettings.map((shift) => <option key={shift.id} value={shift.id}>{shift.label} · {shift.start_time?.slice(0, 5)}–{shift.end_time?.slice(0, 5)} · {shift.timezone} · {shift.effective_from_local?.replace('T', ' ') || '—'}–{shift.effective_until_local?.replace('T', ' ') || '∞'}</option>)}</select></label>{settings && !activeSettings.length && <p>{text.noSettings}</p>}{shiftId && shiftDate && !activeSettings.some((shift) => String(shift.id) === shiftId && roleShiftDateCovered(shift, shiftDate)) && <p role="status" className="inspection-message">{text.outsidePeriod}</p>}<div className="inspection-form-grid">{request.inspection_items.map((item) => <label key={item.id}>{item.label}<select value={itemAreas[item.id] || ''} onChange={(event) => { if (ownsSession()) setItemAreas({ ...itemAreas, [item.id]: event.target.value }); }}><option value="">{text.choose}</option>{inspectionAreas.map((area) => <option key={area} value={area}>{text[area]}</option>)}</select></label>)}</div><label>{text.reason}<textarea maxLength={500} value={reason} onChange={(event) => { if (ownsSession()) setReason(event.target.value); }} /></label><button type="button" className="inspection-button is-primary" disabled={blocked || !shiftId || !shiftDate || !reason.trim() || !activeSettings.some((shift) => String(shift.id) === shiftId && roleShiftDateCovered(shift, shiftDate))} onClick={configure}>{text.configure}</button></fieldset>}</section>}
    <section className="inspection-section"><h3>{text.title}</h3><div className="inspection-role-area-grid">{inspectionAreas.map((area) => {
      const state = workflow.areas.find((row) => row.area === area); const own = state?.assigned_to === userId; const changed = areaDirty(area);
      return <article className="inspection-role-area" key={area}><header><strong>{text[area]}</strong><span className="inspection-status" data-stage={state?.status === 'complete' ? 'completed' : 'waiting'}>{state?.status === 'complete' ? text.completed : text.pending}</span></header><p>{text.owner}: {state?.assigned_to_name || text.unassigned}</p><p>{text.verdict}: {state?.judgement === 'pass' ? text.pass : state?.judgement === 'fail' ? text.fail : '—'}</p>{state?.completed_at && <small>{inspectionTime(state.completed_at, lang)}{state.completed_by_name ? ` · ${state.completed_by_name}` : ''}</small>}
        {own && <><label>{text.verdict}<select disabled={blocked || !state?.can_complete || changed} value={judgements[area]} onChange={(event) => { if (ownsSession()) setJudgements({ ...judgements, [area]: event.target.value as '' | 'pass' | 'fail' }); }}><option value="">{text.choose}</option><option value="pass">{text.pass}</option><option value="fail">{text.fail}</option></select></label><div className="inspection-actions"><button type="button" className="inspection-button" disabled={blocked || !state?.can_save || !changed} onClick={() => saveArea(area)}>{text.save}</button><button type="button" className="inspection-button is-primary" disabled={blocked || changed || !state?.can_complete || !judgements[area]} onClick={() => send('area-complete', { area, area_version: state!.version, config_version: workflow.config_version, judgement: judgements[area] })}>{text.complete}</button></div></>}
        {state?.can_reopen && <button type="button" className="inspection-button" disabled={blocked || dataDirty || !reason.trim()} onClick={() => send('area-reopen', { area, area_version: state.version, config_version: workflow.config_version, reason: reason.trim() })}>{text.reopen}</button>}
      </article>;
    })}</div><p className="inspection-role-final" role="status">{text.final}: <strong>{finalJudgement === 'pass' ? text.bothOk : finalJudgement === 'fail' ? text.failed : text.waiting}</strong></p><p className="inspection-muted">{text.scopeHint}</p></section>
    <section className="inspection-section"><h3 id="inspection-items-title">{common.items}</h3><div className="inspection-table-scroll" role="region" aria-labelledby="inspection-items-title" tabIndex={0}><table className="inspection-items-table"><caption className="sr-only">{common.items}</caption><thead><tr><th scope="col">{common.itemName}</th><th scope="col">{common.criteriaUnit}</th><th scope="col">{common.measurement}</th><th scope="col">{common.judgement}</th></tr></thead><tbody>{request.inspection_items.map((item, index) => {
      const row = measurements.find((entry) => entry.item_id === item.id); const editable = !blocked && inspectionRoleItemEditable(workflow, item.id, userId); const valueId = `inspection-item-${request.id}-${index}-value`; const judgementId = `inspection-item-${request.id}-${index}-judgement`;
      return <tr key={item.id}><th scope="row">{index + 1}. {item.label}<small className="inspection-role-item-area">{workflow.item_areas[item.id] ? text[workflow.item_areas[item.id]] : text.unassigned}</small></th><td className="inspection-item-criterion"><span>{item.required !== false ? common.required : common.optional}{item.unit ? ` · ${item.unit}` : ''}</span>{(item.minimum || item.maximum) && <span>{item.minimum ? `${common.minimum}: ${item.minimum}` : ''}{item.minimum && item.maximum ? ' · ' : ''}{item.maximum ? `${common.maximum}: ${item.maximum}` : ''}</span>}{item.evidence_required && <span>{common.evidenceRequired}</span>}</td><td><label className="sr-only" htmlFor={valueId}>{item.label} · {common.measurement}</label>{item.kind === 'choice' ? <select id={valueId} disabled={!editable} value={row?.value || ''} onChange={(event) => updateMeasurement(item.id, { value: event.target.value })}><option value="">{common.choose}</option>{item.options?.map((option) => <option value={option} key={option}>{option}</option>)}</select> : <input id={valueId} disabled={!editable} maxLength={1000} inputMode={item.kind === 'number' ? 'decimal' : 'text'} value={row?.value || ''} onChange={(event) => updateMeasurement(item.id, { value: event.target.value })} />}{!editable && [...(row?.value || '')].length > 8 && <details className="inspection-help inspection-full-value"><summary><span aria-hidden="true">ⓘ</span> {common.fullValue}</summary><p>{row?.value}</p></details>}</td><td><label className="sr-only" htmlFor={judgementId}>{item.label} · {common.judgement}</label><select id={judgementId} disabled={!editable} value={row?.judgement || ''} onChange={(event) => updateMeasurement(item.id, { judgement: event.target.value as InspectionMeasurement['judgement'] })}><option value="">{common.choose}</option><option value="pass">{text.pass}</option><option value="fail">{text.fail}</option></select></td></tr>;
    })}</tbody></table></div>{!workflow.my_item_ids.length && <p className="inspection-muted">{text.noPermission}</p>}</section>
    <details className="inspection-help inspection-evidence-help"><summary><span aria-hidden="true">ⓘ</span> {common.attachments}</summary><div className="inspection-item-evidence-fields">{request.inspection_items.map((item, index) => { const row = measurements.find((entry) => entry.item_id === item.id); const link = safeInspectionEvidenceUrl(row?.evidence_url || ''); return <div key={item.id}><label>{index + 1}. {item.label} · {common.itemEvidence}<input type="url" maxLength={500} disabled={blocked || !inspectionRoleItemEditable(workflow, item.id, userId)} value={row?.evidence_url || ''} onChange={(event) => updateMeasurement(item.id, { evidence_url: event.target.value })} /></label>{link && <a href={link} target="_blank" rel="noopener noreferrer">{common.openEvidence}</a>}</div>; })}</div>{inspectionAreas.map((area) => { const state = workflow.areas.find((row) => row.area === area); const editable = !blocked && state?.assigned_to === userId && state.can_save; return <div key={area}><h4>{text[area]} · {common.evidence}</h4>{evidence[area].map((row, index) => <div className="inspection-evidence-row" key={index}><label>{common.evidenceName}<input maxLength={128} disabled={!editable} value={row.label} onChange={(event) => { if (ownsSession()) setEvidence({ ...evidence, [area]: evidence[area].map((entry, i) => i === index ? { ...entry, label: event.target.value } : entry) }); }} /></label><label>{common.evidenceUrl}<input type="url" maxLength={500} disabled={!editable} value={row.url} onChange={(event) => { if (ownsSession()) setEvidence({ ...evidence, [area]: evidence[area].map((entry, i) => i === index ? { ...entry, url: event.target.value } : entry) }); }} /></label><button type="button" className="inspection-button" disabled={!editable} onClick={() => { if (ownsSession()) setEvidence({ ...evidence, [area]: evidence[area].filter((_, i) => i !== index) }); }}>{common.remove}</button></div>)}<button type="button" className="inspection-button" disabled={!editable || evidence[area].length >= 10} onClick={() => { if (ownsSession()) setEvidence({ ...evidence, [area]: [...evidence[area], { label: '', url: '' }] }); }}>{common.addEvidence}</button></div>; })}</details>
    <section className="inspection-section"><h3>{common.results}</h3><div className="inspection-form-grid">{request.quantity_mode === 'recorded' && (['inspected_quantity', 'accepted_quantity', 'rejected_quantity'] as const).map((name) => <label key={name}>{name === 'inspected_quantity' ? common.inspected : name === 'accepted_quantity' ? common.accepted : common.rejected} ({request.uom})<input maxLength={30} inputMode="decimal" disabled={!canSummaryEdit} value={summary[name]} onChange={(event) => { if (ownsSession()) setSummary({ ...summary, [name]: event.target.value }); }} /></label>)}<label className="inspection-form-full">{common.notes}<textarea maxLength={2000} disabled={!canSummaryEdit} value={summary.notes} onChange={(event) => { if (ownsSession()) setSummary({ ...summary, notes: event.target.value }); }} /></label></div><div className="inspection-actions"><button type="button" className="inspection-button" disabled={!canSummaryEdit || !summaryDirty} onClick={() => send('role-results', { version: request.version, ...summary, ...(request.quantity_mode === 'not_recorded' ? { inspected_quantity: '0', accepted_quantity: '0', rejected_quantity: '0' } : {}) })}>{common.save}</button><button type="button" className="inspection-button is-primary" disabled={blocked || dirty || !request.capabilities.can_submit || !finalJudgement} onClick={() => send('submit', { version: request.version, reason: '' }, 'legacy')}>{common.submit}</button><button type="button" className="inspection-button" disabled={busy || Boolean(attempt)} onClick={() => { if (!dirty || window.confirm(common.discard)) void getInspectionRequest(request.id, sessionId).then((updated) => { if (ownsSession()) { setSummary(summaryDraft(updated)); adopt(updated); } }).catch((cause) => { if (ownsSession()) setError(inspectionError(cause, common.loadError).message); }); }}>{common.reload}</button></div>{dirty && <p className="inspection-muted" role="status">{text.draft}</p>}</section>
    <details className="inspection-section inspection-fold" open={request.capabilities.can_review || request.capabilities.can_reinspect || workflow.areas.some((area) => area.can_reopen)}><summary>{common.review}</summary>{request.review_reason && <p>{common.reviewReason}: {request.review_reason}</p>}<label>{text.reason}<textarea disabled={blocked} maxLength={500} value={reason} onChange={(event) => { if (ownsSession()) setReason(event.target.value); }} /></label><div className="inspection-actions">{request.capabilities.can_review_failure && <button type="button" className="inspection-button" disabled={blocked || dataDirty || request.submitted_by === userId || !reason.trim()} onClick={() => send('review-failure', { version: request.version, reason: reason.trim() }, 'legacy')}>{lang === 'ko' ? '불합격 결과 검수 승인' : '审核不合格检验结果'}</button>}<button type="button" className="inspection-button" disabled={blocked || dataDirty || !request.capabilities.can_review || request.submitted_by === userId} onClick={() => send('approve', { version: request.version, reason: reason.trim() }, 'legacy')}>{common.approve}</button><button type="button" className="inspection-button" disabled={blocked || dataDirty || !request.capabilities.can_review || request.submitted_by === userId || !reason.trim()} onClick={() => send('reject', { version: request.version, reason: reason.trim() }, 'legacy')}>{common.reject}</button><button type="button" className="inspection-button" disabled={blocked || dataDirty || !request.capabilities.can_reinspect || !reason.trim()} onClick={() => send('reinspect', { version: request.version, reason: reason.trim() }, 'legacy')}>{common.reinspect}</button></div></details>
    <section className="inspection-section"><h3>{common.mes}</h3><p className="inspection-muted">{text.mesBlocked}</p><div className="inspection-actions"><button type="button" className="inspection-button" disabled>{text.mesPartial}</button><button type="button" className="inspection-button" disabled>{common.mesFinish}</button></div><details className="inspection-help"><summary><span aria-hidden="true">ⓘ</span> {text.mesPartial}</summary><p>{text.mesHint}</p></details></section>
    <details className="inspection-help inspection-fold"><summary><span aria-hidden="true">ⓘ</span> {lang === 'ko' ? '작업 정보·검사 기준' : '作业信息·检验规则'}</summary><dl className="inspection-meta"><div><dt>{common.workOrder}</dt><dd>{request.work_order_ref}</dd></div><div><dt>{common.task}</dt><dd>{request.task_ref}</dd></div><div><dt>{common.owner}</dt><dd>{request.assigned_to_name || text.unassigned}</dd></div><div><dt>{common.version}</dt><dd>{request.version}</dd></div>{workflow.shift_snapshot && <><div><dt>{text.label}</dt><dd>{workflow.shift_snapshot.label} · {workflow.shift_snapshot.shift_date || '—'} · {workflow.shift_snapshot.start_time?.slice(0, 5)}–{workflow.shift_snapshot.end_time?.slice(0, 5)} · {workflow.shift_snapshot.timezone}</dd></div><div><dt>{text.fromLocal}</dt><dd>{workflow.shift_snapshot.effective_from_local?.replace('T', ' ') || '—'}</dd></div><div><dt>{text.untilLocal}</dt><dd>{workflow.shift_snapshot.effective_until_local?.replace('T', ' ') || '—'}</dd></div><div><dt>{text.fromUTC}</dt><dd>{workflow.shift_snapshot.effective_from || '—'}</dd></div><div><dt>{text.untilUTC}</dt><dd>{workflow.shift_snapshot.effective_until || '—'}</dd></div></>}</dl></details>
    <details className="inspection-section inspection-fold inspection-handling-history"><summary>{common.handlingHistory} ({historyRows.length})</summary>{historyRows.length ? <div className="inspection-table-scroll" tabIndex={0} role="region" aria-label={common.handlingHistory}><table className="inspection-history-table"><caption className="sr-only">{common.handlingHistory}</caption><thead><tr><th scope="col">{common.historyTime}</th><th scope="col">{common.historyActor}</th><th scope="col">{common.historyAction}</th><th scope="col">{common.historyResult}</th></tr></thead><tbody>{historyRows.map((row) => <tr key={row.key}><td>{inspectionTime(row.at, lang)}</td><td>{row.actor}</td><td>{row.action}</td><td>{row.result}</td></tr>)}</tbody></table></div> : <p className="inspection-muted">{common.noOperations}</p>}</details>
  </section>;
}
