export const inspectionRoleCopy = {
  ko: {
    title: '외관·치수 분담', appearance: '외관', dimension: '치수', settings: '교대·담당 설정',
    optIn: '외관·치수를 나누어 검사', optInHint: '생성 후 교대와 담당자, 항목 영역을 명시적으로 설정합니다. 기존 검사에는 적용하지 않습니다.',
    empty: '교대·담당이 아직 설정되지 않았습니다.', configuration: '이 검사 담당 설정', configure: '설정 적용',
    label: '교대 이름', timezone: '시간대', start: '시작 시각', end: '종료 시각', owner: 'WJ 입력 담당', choose: '선택하세요',
    active: '사용', newSetting: '교대 설정 추가', saveSetting: '교대 설정 저장', reason: '변경 사유',
    save: '내 영역 저장', complete: '내 영역 검사 완료', reopen: '영역 검사 다시 열기', verdict: '영역 판정',
    final: '최종 판정', bothOk: '외관·치수 모두 완료·OK', waiting: '두 영역 완료·OK 대기', failed: '불합격',
    pending: '미완료', completed: '완료', pass: 'OK', fail: 'NG', unassigned: '미배정',
    mesPartial: 'MES 담당 항목 저장', mesBlocked: 'MES 부분 저장 계약 미확인 · 실행자 확인 필요',
    mesHint: 'WJ 입력 담당과 MES 실행자는 별도입니다. 한 QC의 복수 실행자, 다른 항목 보존 및 동시 저장 계약이 확인될 때까지 MES 저장·완료는 사용할 수 없습니다.',
    scopeHint: '본인에게 배정된 영역만 입력합니다. 영역 저장은 다른 담당자의 결과를 변경하지 않습니다.',
    configurationHint: '실제 계정과 교대 시각을 확인한 뒤 설정하세요. 입력을 시작한 검사의 담당과 항목 영역은 바꿀 수 없습니다.',
    noSettings: '저장된 교대 설정이 없습니다. 교대·담당 설정에서 추가하세요.',
    denied: '설정은 현재 설정 권한이 있는 계정에서 가능합니다.',
    invalid: '교대 이름·시간대·시각과 서로 다른 외관·치수 담당자를 모두 선택하세요.',
    mappingInvalid: '각 항목 영역을 선택하고 외관·치수에 각각 하나 이상의 항목을 배정하세요.',
    saved: '저장했습니다.', conflict: '다른 변경이 먼저 저장되었습니다. 내 입력은 보존했습니다. 최신 상태와 비교 후 명시적으로 반영하세요.',
    compare: '최신 상태 비교', useDraft: '최신 버전에 내 입력 반영 준비', discard: '내 입력 버리고 최신 상태 사용',
    uncertain: '저장 결과를 확인하지 못했습니다. 동일 요청으로 결과를 확인하거나 최신 상태를 읽으세요.',
    retry: '동일 요청 결과 확인', draft: '내 영역에 저장하지 않은 입력이 있습니다.',
    legacy: '기존 검사 방식', noPermission: '현재 계정에 배정된 편집 항목이 없습니다.',
  },
  zh: {
    title: '外观·尺寸分工', appearance: '外观', dimension: '尺寸', settings: '班次·人员设置',
    optIn: '分开进行外观与尺寸检验', optInHint: '创建后明确设置班次、人员及项目区域。不应用于现有检验。',
    empty: '尚未设置班次与人员。', configuration: '设置本次检验分工', configure: '应用设置',
    label: '班次名称', timezone: '时区', start: '开始时间', end: '结束时间', owner: 'WJ 录入人员', choose: '请选择',
    active: '启用', newSetting: '新增班次设置', saveSetting: '保存班次设置', reason: '变更原因',
    save: '保存我的区域', complete: '完成我的区域检验', reopen: '重新打开区域检验', verdict: '区域判定',
    final: '最终判定', bothOk: '外观·尺寸均已完成且 OK', waiting: '等待两个区域完成且 OK', failed: '不合格',
    pending: '未完成', completed: '已完成', pass: 'OK', fail: 'NG', unassigned: '未分配',
    mesPartial: '保存 MES 负责项目', mesBlocked: 'MES 部分保存合同未确认 · 需确认执行人',
    mesHint: 'WJ 录入人员与 MES 执行人分别记录。单个 QC 的多人执行、其他项目保留及并发保存合同确认前，不可执行 MES 保存或完成。',
    scopeHint: '只能输入分配给自己的区域。区域保存不会更改其他人员的结果。',
    configurationHint: '请确认实际账号及班次时间后设置。开始录入后的检验不可更改人员或项目区域。',
    noSettings: '暂无已保存的班次设置。请在班次·人员设置中新增。', denied: '仅当前具备设置权限的账号可以配置。',
    invalid: '请填写班次名称、时区与时间，并选择不同的外观和尺寸人员。',
    mappingInvalid: '请选择每个项目的区域，并为外观与尺寸各分配至少一个项目。',
    saved: '已保存。', conflict: '其他变更已先保存。已保留我的输入。请对比最新状态后明确处理。',
    compare: '对比最新状态', useDraft: '准备将我的输入应用至最新版本', discard: '放弃我的输入并使用最新状态',
    uncertain: '未确认保存结果。请使用同一请求确认结果，或读取最新状态。', retry: '确认同一请求结果', draft: '我的区域有未保存的输入。',
    legacy: '现有检验方式', noPermission: '当前账号未分配可编辑项目。',
  },
};
