export const inspectionRoleCopy = {
  ko: {
    title: '외관·치수 분담', appearance: '외관', dimension: '치수', settings: '교대·담당 설정',
    optIn: '외관·치수를 나누어 검사', optInHint: '생성 후 교대와 담당자, 항목 영역을 명시적으로 설정합니다. 기존 검사에는 적용하지 않습니다.',
    empty: '교대·담당이 아직 설정되지 않았습니다.', configuration: '이 검사 담당 설정', configure: '설정 적용',
    label: '교대 이름', timezone: '시간대', start: '시작 시각', end: '종료 시각', owner: 'WJ 입력 담당', choose: '선택하세요',
    active: '이 기간 사용', newSetting: '새 기간 행 추가', saveSetting: '교대 설정 저장', reason: '변경 사유',
    preset: '교대 기본값', day: '주간', night: '야간', custom: '직접 시각 지정',
    fromLocal: '적용 시작 · 중국 현지', untilLocal: '적용 종료 · 중국 현지', untilOptional: '종료 미입력 시 기한 없이 적용',
    chinaTime: '중국 현지 · Asia/Shanghai (UTC+08:00)', editExisting: '기존 기간 행 수정', createPeriod: '새 기간 행 작성',
    periodHint: '매일 주간 08:00–20:00, 야간 20:00–다음날 08:00. 화면 기본값이며 담당자·기간을 저장하기 전에는 적용되지 않습니다.',
    periodBoundaryHint: '적용 시작은 교대 시작 시각, 종료는 시작 또는 종료 시각에 맞추세요. 야간 00:00은 전날 시작한 교대에 속하며 08:00·20:00에서 교대가 바뀝니다.',
    preserveSnapshotHint: '기존 행 수정은 이후 검사 설정에 적용합니다. 이미 시작한 검사의 담당·교대 스냅샷은 보존합니다. 다른 적용 기간은 새 행으로 추가하세요.',
    accountHint: 'WJ 이름·계정과 알려진 MES USER 식별자입니다. 연결 식별자만으로 MES 권한이나 검사 실행자가 확인되지는 않습니다.',
    utcRecord: '서버 저장 · UTC', fromUTC: '적용 시작 · UTC', untilUTC: '적용 종료 · UTC', internalCode: '내부 설정 식별자', outsidePeriod: '선택한 날짜의 교대 전체가 이 설정의 적용 기간에 포함되어야 합니다.',
    overlap: '사용 중인 다른 기간·교대와 시간이 겹칩니다. 적용 기간과 시각을 확인하세요.', duplicate: '설정 식별자가 이미 사용 중입니다. 입력을 보존한 상태에서 새 기간 행을 다시 준비하세요.',
    datetimeInvalid: '중국 현지 날짜와 시각을 YYYY-MM-DDTHH:mm 형식으로 지정하세요.', periodOrder: '적용 종료는 적용 시작보다 늦어야 합니다.',
    fromRequired: '사용할 기간의 적용 시작 날짜·시각을 명시적으로 지정하세요.', fromAlignment: '적용 시작 시각은 이 교대의 시작 시각과 같아야 합니다.',
    untilAlignment: '적용 종료 시각은 이 교대의 시작 또는 종료 시각에 맞춰야 합니다.', ineligible: '현재 선택 가능한 계정에서 담당자를 선택하세요.',
    save: '내 영역 저장', complete: '내 영역 검사 완료', reopen: '영역 검사 다시 열기', verdict: '영역 판정',
    final: '최종 판정', bothOk: '외관·치수 모두 완료·OK', waiting: '두 영역 완료·OK 대기', failed: '불합격',
    pending: '미완료', completed: '완료', pass: 'OK', fail: 'NG', unassigned: '미배정',
    mesPartial: 'MES 담당 항목 저장', mesBlocked: 'MES 부분 저장 계약 미확인 · 실행자 확인 필요',
    mesHint: 'WJ 입력 담당과 MES 실행자는 별도입니다. 한 QC의 복수 실행자, 다른 항목 보존 및 동시 저장 계약이 확인될 때까지 MES 저장·완료는 사용할 수 없습니다.',
    scopeHint: '본인에게 배정된 영역만 입력합니다. 영역 저장은 다른 담당자의 결과를 변경하지 않습니다.',
    configurationHint: '실제 계정과 교대 시각을 확인한 뒤 설정하세요. 입력을 시작한 검사의 담당과 항목 영역은 바꿀 수 없습니다.',
    noSettings: '저장된 교대 설정이 없습니다. 교대·담당 설정에서 추가하세요.',
    denied: '설정은 현재 설정 권한이 있는 계정에서 가능합니다.',
    invalid: '교대 이름·시간대·시각과 서로 다른 외관·치수 담당자를 모두 선택하세요.',
    mappingInvalid: '각 항목 영역을 선택하고 외관·치수에 각각 하나 이상의 항목을 배정하세요.',
    saved: '저장했습니다.', conflict: '다른 변경이 먼저 저장되었습니다. 내 입력은 보존했습니다. 최신 상태와 비교 후 명시적으로 반영하세요.',
    compare: '최신 상태 비교', useDraft: '최신 버전에 내 입력 반영 준비', discard: '내 입력 버리고 최신 상태 사용',
    uncertain: '저장 결과를 확인하지 못했습니다. 동일 요청으로 결과를 확인하거나 최신 상태를 읽으세요.',
    retry: '동일 요청 결과 확인', draft: '내 영역에 저장하지 않은 입력이 있습니다.',
    legacy: '기존 검사 방식', noPermission: '현재 계정에 배정된 편집 항목이 없습니다.',
  },
  zh: {
    title: '外观·尺寸分工', appearance: '外观', dimension: '尺寸', settings: '班次·人员设置',
    optIn: '分开进行外观与尺寸检验', optInHint: '创建后明确设置班次、人员及项目区域。不应用于现有检验。',
    empty: '尚未设置班次与人员。', configuration: '设置本次检验分工', configure: '应用设置',
    label: '班次名称', timezone: '时区', start: '开始时间', end: '结束时间', owner: 'WJ 录入人员', choose: '请选择',
    active: '启用此期间', newSetting: '新增期间记录', saveSetting: '保存班次设置', reason: '变更原因',
    preset: '班次默认值', day: '白班', night: '夜班', custom: '自定义时间',
    fromLocal: '生效开始 · 中国当地', untilLocal: '生效结束 · 中国当地', untilOptional: '留空结束时间表示无期限',
    chinaTime: '中国当地 · Asia/Shanghai (UTC+08:00)', editExisting: '修改现有期间记录', createPeriod: '新增期间记录草稿',
    periodHint: '每天白班 08:00–20:00，夜班 20:00–次日 08:00。这些仅为界面默认值，人员与期间保存前不生效。',
    periodBoundaryHint: '生效开始需与班次开始时间对齐，结束需与开始或结束时间对齐。夜班 00:00 属于前一天开始的班次，08:00 与 20:00 换班。',
    preserveSnapshotHint: '修改现有记录仅影响后续检验设置。已开始检验的人员·班次快照保持不变。其他生效期间请新增记录。',
    accountHint: '显示 WJ 姓名·账号及已知 MES USER 标识。关联标识本身不能证明 MES 权限或检验执行人。',
    utcRecord: '服务器存储 · UTC', fromUTC: '生效开始 · UTC', untilUTC: '生效结束 · UTC', internalCode: '内部设置标识', outsidePeriod: '所选日期的整个班次必须处于此设置的生效期间内。',
    overlap: '与已启用的其他期间·班次重叠。请检查生效期间与时间。', duplicate: '设置标识已被使用。保留输入并重新准备新增期间记录。',
    datetimeInvalid: '请按 YYYY-MM-DDTHH:mm 指定中国当地日期与时间。', periodOrder: '生效结束须晚于生效开始。',
    fromRequired: '请明确指定启用期间的开始日期与时间。', fromAlignment: '生效开始时间须与此班次开始时间一致。',
    untilAlignment: '生效结束时间须与此班次的开始或结束时间对齐。', ineligible: '请从当前可选账号中选择人员。',
    save: '保存我的区域', complete: '完成我的区域检验', reopen: '重新打开区域检验', verdict: '区域判定',
    final: '最终判定', bothOk: '外观·尺寸均已完成且 OK', waiting: '等待两个区域完成且 OK', failed: '不合格',
    pending: '未完成', completed: '已完成', pass: 'OK', fail: 'NG', unassigned: '未分配',
    mesPartial: '保存 MES 负责项目', mesBlocked: 'MES 部分保存合同未确认 · 需确认执行人',
    mesHint: 'WJ 录入人员与 MES 执行人分别记录。单个 QC 的多人执行、其他项目保留及并发保存合同确认前，不可执行 MES 保存或完成。',
    scopeHint: '只能输入分配给自己的区域。区域保存不会更改其他人员的结果。',
    configurationHint: '请确认实际账号及班次时间后设置。开始录入后的检验不可更改人员或项目区域。',
    noSettings: '暂无已保存的班次设置。请在班次·人员设置中新增。', denied: '仅当前具备设置权限的账号可以配置。',
    invalid: '请填写班次名称、时区与时间，并选择不同的外观和尺寸人员。',
    mappingInvalid: '请选择每个项目的区域，并为外观与尺寸各分配至少一个项目。',
    saved: '已保存。', conflict: '其他变更已先保存。已保留我的输入。请对比最新状态后明确处理。',
    compare: '对比最新状态', useDraft: '准备将我的输入应用至最新版本', discard: '放弃我的输入并使用最新状态',
    uncertain: '未确认保存结果。请使用同一请求确认结果，或读取最新状态。', retry: '确认同一请求结果', draft: '我的区域有未保存的输入。',
    legacy: '现有检验方式', noPermission: '当前账号未分配可编辑项目。',
  },
};
